const escapeHtml=(value:unknown)=>String(value??'').replace(/[&<>"']/g,(ch)=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]||ch));

export function exportTableToExcel(filename:string,headers:string[],rows:Array<Array<string|number|null|undefined>>){
 const table=`<table><thead><tr>${headers.map(h=>`<th>${escapeHtml(h)}</th>`).join('')}</tr></thead><tbody>${rows.map(row=>`<tr>${row.map(v=>`<td>${escapeHtml(v)}</td>`).join('')}</tr>`).join('')}</tbody></table>`;
 const html=`<html><head><meta charset="UTF-8"></head><body>${table}</body></html>`;
 const blob=new Blob(['\ufeff',html],{type:'application/vnd.ms-excel;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=filename.endsWith('.xls')?filename:`${filename}.xls`;document.body.appendChild(a);a.click();a.remove();window.setTimeout(()=>URL.revokeObjectURL(url),1500);
}

/* Generates a printable report in a hidden iframe instead of window.open.
   This avoids popup blockers, which were the reason PDF appeared to do nothing.
   Browser print lets the operator choose "Guardar como PDF" on all supported desktops. */
export function printTableAsPdf(title:string,headers:string[],rows:Array<Array<string|number|null|undefined>>){
 const table=`<table><thead><tr>${headers.map(h=>`<th>${escapeHtml(h)}</th>`).join('')}</tr></thead><tbody>${rows.map(row=>`<tr>${row.map(v=>`<td>${escapeHtml(v)}</td>`).join('')}</tr>`).join('')}</tbody></table>`;
 const html=`<!doctype html><html><head><meta charset="utf-8"><title>${escapeHtml(title)}</title><style>body{font-family:Arial,sans-serif;color:#111;padding:18px}h1{font-size:19px;margin:0 0 5px}p{font-size:10px;color:#666;margin:0 0 14px}table{border-collapse:collapse;width:100%;font-size:8.5px}th,td{border:1px solid #aaa;padding:5px;text-align:left;vertical-align:top;word-break:break-word}th{background:#eee}@page{size:landscape;margin:9mm}</style></head><body><h1>${escapeHtml(title)}</h1><p>Generado por Central GO · ${new Date().toLocaleString('es-CL')}</p>${table}</body></html>`;
 const frame=document.createElement('iframe');frame.style.position='fixed';frame.style.right='0';frame.style.bottom='0';frame.style.width='1px';frame.style.height='1px';frame.style.border='0';frame.style.opacity='0';frame.setAttribute('aria-hidden','true');document.body.appendChild(frame);
 const doc=frame.contentDocument;if(!doc){frame.remove();throw new Error('No fue posible preparar el informe PDF.');}doc.open();doc.write(html);doc.close();
 window.setTimeout(()=>{try{const win=frame.contentWindow;if(!win)throw new Error('No fue posible abrir el informe PDF.');win.focus();win.print();}finally{window.setTimeout(()=>frame.remove(),2000);}},250);
}

export function printAnalyticsReport(input:{title:string;period:string;kpis:Array<{label:string;value:string}>;series:Array<{label:string;trips:number;amount:number}>;driverHeaders:string[];driverRows:Array<Array<string|number|null|undefined>>;operationHeaders:string[];operationRows:Array<Array<string|number|null|undefined>>}){
 const maxTrips=Math.max(1,...input.series.map(item=>item.trips)),maxAmount=Math.max(1,...input.series.map(item=>item.amount));
 const kpis=input.kpis.map(item=>`<div class="kpi"><span>${escapeHtml(item.label)}</span><strong>${escapeHtml(item.value)}</strong></div>`).join('');
 const graph=input.series.map(item=>`<div class="bar-row"><b>${escapeHtml(item.label)}</b><div class="track"><i style="width:${Math.max(1,item.trips/maxTrips*100)}%"></i></div><span>${item.trips} carreras</span><div class="track money"><i style="width:${Math.max(1,item.amount/maxAmount*100)}%"></i></div><span>$${Math.round(item.amount).toLocaleString('es-CL')}</span></div>`).join('');
 const table=(headers:string[],rows:Array<Array<string|number|null|undefined>>)=>`<table><thead><tr>${headers.map(h=>`<th>${escapeHtml(h)}</th>`).join('')}</tr></thead><tbody>${rows.map(row=>`<tr>${row.map(v=>`<td>${escapeHtml(v)}</td>`).join('')}</tr>`).join('')}</tbody></table>`;
 const html=`<!doctype html><html><head><meta charset="utf-8"><title>${escapeHtml(input.title)}</title><style>*{box-sizing:border-box}body{font-family:Arial,sans-serif;color:#15171a;padding:18px}h1{font-size:21px;margin:0}h2{font-size:13px;margin:18px 0 8px}.meta{font-size:10px;color:#666;margin:4px 0 14px}.kpis{display:grid;grid-template-columns:repeat(5,1fr);gap:7px}.kpi{border:1px solid #ccd0d5;border-radius:8px;padding:9px;background:#f5f6f7}.kpi span{display:block;font-size:7px;text-transform:uppercase;color:#666}.kpi strong{display:block;font-size:15px;margin-top:4px}.graph{border:1px solid #ccd0d5;border-radius:8px;padding:10px}.bar-row{display:grid;grid-template-columns:38px 1fr 62px 1fr 75px;align-items:center;gap:6px;margin:5px 0;font-size:7px}.track{height:8px;border-radius:5px;background:#e4e7ea;overflow:hidden}.track i{display:block;height:100%;background:#252a30}.track.money i{background:#737b85}table{border-collapse:collapse;width:100%;font-size:7px;page-break-inside:auto}tr{page-break-inside:avoid}th,td{border:1px solid #c5c9ce;padding:4px;text-align:left;vertical-align:top;word-break:break-word}th{background:#252a30;color:white}@page{size:landscape;margin:8mm}</style></head><body><h1>${escapeHtml(input.title)}</h1><p class="meta">${escapeHtml(input.period)} · Generado por Central GO ${new Date().toLocaleString('es-CL')}</p><div class="kpis">${kpis}</div><h2>Actividad por hora</h2><div class="graph">${graph||'<p>Sin operaciones en el periodo.</p>'}</div><h2>Rendimiento por conductor</h2>${table(input.driverHeaders,input.driverRows)}<h2>Registro de cada operación</h2>${table(input.operationHeaders,input.operationRows)}</body></html>`;
 const frame=document.createElement('iframe');frame.style.cssText='position:fixed;right:0;bottom:0;width:1px;height:1px;border:0;opacity:0';frame.setAttribute('aria-hidden','true');document.body.appendChild(frame);const doc=frame.contentDocument;if(!doc){frame.remove();throw new Error('No fue posible preparar el informe.');}doc.open();doc.write(html);doc.close();window.setTimeout(()=>{try{frame.contentWindow?.focus();frame.contentWindow?.print();}finally{window.setTimeout(()=>frame.remove(),2000);}},300);
}
