import React,{useEffect,useId,useMemo,useRef,useState}from'react';
import{CalendarClock,Car,ChevronDown,CircleDollarSign,Clock3,MapPin,MessageSquareText,Navigation,Phone,Send,Sparkles,UserRound,X,Zap}from'lucide-react';
import{useApp}from'../../context/AppContext';
import type{FareDestination,PaymentMethod}from'../../types';
import{runtimeConfig}from'../../config/runtime';
import{geocodeCommercialAddress}from'../../lib/geocoding';
import{loadClientDriverBlocks,loadFareDestinations}from'../../lib/operationalIntelligenceRepository';

const norm=(v:string)=>v.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim();
const nextHourLocal=()=>{const d=new Date(Date.now()+3600000);d.setMinutes(0,0,0);const p=(n:number)=>String(n).padStart(2,'0');return`${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())}T${p(d.getHours())}:${p(d.getMinutes())}`;};

export const NewTripModal:React.FC=()=>{
 const{newTripModalOpen,setNewTripModalOpen,clients,drivers,trips,createTrip,fareConfig,currentCompany}=useApp();
 const originRef=useRef<HTMLInputElement>(null);
 const[origin,setOrigin]=useState(''),[destination,setDestination]=useState('A convenir / Taxímetro'),[clientId,setClientId]=useState(''),[clientName,setClientName]=useState('Cliente Particular'),[clientPhone,setClientPhone]=useState(''),[payment,setPayment]=useState<PaymentMethod>('efectivo'),[notes,setNotes]=useState(''),[vehicleType,setVehicleType]=useState<'standard'|'pet'|'wheelchair'|'vip'>('standard'),[driverId,setDriverId]=useState(''),[km,setKm]=useState(3),[scheduled,setScheduled]=useState(false),[scheduledLocal,setScheduledLocal]=useState(nextHourLocal()),[fixedFare,setFixedFare]=useState(false),[fixedAmount,setFixedAmount]=useState(4500),[fares,setFares]=useState<FareDestination[]>([]),[blockedDriverIds,setBlockedDriverIds]=useState<Set<string>>(new Set()),[error,setError]=useState(''),[submitting,setSubmitting]=useState(false);
 const addressCache=useMemo(()=>{const seen=new Set<string>(),result:string[]=[];const add=(v?:string)=>{const c=v?.trim();if(!c||c.length<3||/^a convenir/i.test(c)||seen.has(norm(c)))return;seen.add(norm(c));result.push(c);};trips.slice(0,500).forEach(t=>{add(t.origin.address);add(t.destination.address);});clients.forEach(c=>c.frequentAddresses.forEach(a=>add(a.address)));return result.slice(0,80);},[trips,clients]);
 const fareMatch=useMemo(()=>{const d=norm(destination);if(!d||/^a convenir/.test(d))return undefined;return fares.find(f=>f.active&&(d.includes(norm(f.matchText))||d.includes(norm(f.name))));},[destination,fares]);
 useEffect(()=>{if(!newTripModalOpen)return;setError('');window.setTimeout(()=>originRef.current?.focus(),50);void loadFareDestinations(currentCompany.id).then(setFares).catch(()=>setFares([]));},[newTripModalOpen,currentCompany.id]);
 useEffect(()=>{if(fareMatch){setFixedFare(true);setFixedAmount(fareMatch.fareAmount);}},[fareMatch?.id]);
 useEffect(()=>{if(!clientId){setBlockedDriverIds(new Set());return;}void loadClientDriverBlocks(currentCompany.id,clientId).then(rows=>setBlockedDriverIds(new Set(rows.map(r=>r.driverId)))).catch(()=>setBlockedDriverIds(new Set()));},[clientId,currentCompany.id]);
 const available=useMemo(()=>drivers.filter(d=>d.status==='available'&&!blockedDriverIds.has(d.id)),[drivers,blockedDriverIds]);
 const calculated=fixedFare?Math.max(0,fixedAmount):Math.round(fareConfig.baseFare+Math.max(.5,km)*fareConfig.pricePerKm);
 const close=()=>{setNewTripModalOpen(false);setError('');};
 const selectClient=(id:string)=>{setClientId(id);const c=clients.find(x=>x.id===id);if(!c){setClientName('Cliente Particular');setClientPhone('');return;}setClientName(c.name);setClientPhone(c.phone);if(c.frequentAddresses[0])setOrigin(c.frequentAddresses[0].address);if(c.hasCurrentAccount)setPayment('cuenta_corriente');};
 const submit=async(e:React.FormEvent)=>{e.preventDefault();const cleanOrigin=origin.trim(),cleanDestination=destination.trim()||'A convenir / Taxímetro';if(cleanOrigin.length<3){setError('Escribe la dirección de retiro.');originRef.current?.focus();return;}let scheduledFor:string|undefined;if(scheduled){const date=new Date(scheduledLocal);if(Number.isNaN(date.getTime())||date.getTime()<Date.now()+120000){setError('La carrera agendada debe ser al menos 2 minutos después.');return;}scheduledFor=date.toISOString();}const selected=scheduled?undefined:available.find(d=>d.id===driverId);setSubmitting(true);try{const originPoint=runtimeConfig.isCommercial?await geocodeCommercialAddress(currentCompany.id,cleanOrigin):{lat:-35.8454,lng:-71.5979};const unknown=/^a convenir/i.test(cleanDestination);const destPoint=runtimeConfig.isCommercial?(unknown?originPoint:await geocodeCommercialAddress(currentCompany.id,cleanDestination)):{lat:-35.849,lng:-71.603};await createTrip({clientId:clientId||undefined,clientName:clientName.trim()||'Cliente Particular',clientPhone:clientPhone.trim()||'Sin teléfono',origin:{...originPoint,address:cleanOrigin},destination:{...destPoint,address:cleanDestination},driverId:selected?.id,driverUnitNumber:selected?.unitNumber,driverName:selected?.name,dispatchMode:selected?'manual':'automatic',scheduledFor,vehicleTypeRequested:vehicleType,paymentMethod:payment,notes:notes.trim()||undefined,estimatedDistanceKm:Math.max(.5,km),estimatedDurationMins:Math.max(5,Math.round(km*3)),estimatedFare:calculated,isFixedFare:fixedFare,fixedFareAmount:fixedFare?Math.max(0,fixedAmount):undefined});setNewTripModalOpen(false);setOrigin('');setDestination('A convenir / Taxímetro');setDriverId('');setClientId('');setClientName('Cliente Particular');setClientPhone('');setNotes('');setPayment('efectivo');setScheduled(false);setFixedFare(false);}catch(err){setError(err instanceof Error?err.message:'No fue posible crear la carrera.');}finally{setSubmitting(false);}};
 if(!newTripModalOpen)return null;
 return <div className="fixed inset-0 z-50 flex items-start justify-center overflow-y-auto bg-black/80 p-3 backdrop-blur-sm sm:items-center"><div className="my-3 w-full max-w-3xl overflow-hidden rounded-3xl border border-zinc-700 bg-[#0d0d0f] shadow-2xl"><header className="flex items-center justify-between border-b border-zinc-800 px-4 py-4 sm:px-6"><div className="flex items-center gap-3"><div className="rounded-2xl bg-amber-400 p-3 text-zinc-950"><Zap className="h-5 w-5"/></div><div><h2 className="text-xl font-black text-white">Nueva carrera</h2><p className="text-xs text-zinc-500">Despacho rápido con memoria de direcciones, tarifa y equidad automática.</p></div></div><button onClick={close} className="p-2 text-zinc-500"><X className="h-5 w-5"/></button></header><form onSubmit={submit} className="space-y-4 p-4 sm:p-6">
  <div className="grid grid-cols-2 gap-2 rounded-2xl border border-zinc-800 bg-zinc-950/60 p-1.5"><button type="button" onClick={()=>{setScheduled(false);setDriverId('');}} className={`rounded-xl px-3 py-2.5 text-sm font-black ${!scheduled?'bg-amber-400 text-zinc-950':'text-zinc-400'}`}><Zap className="mr-1 inline h-4 w-4"/>Ahora</button><button type="button" onClick={()=>{setScheduled(true);setDriverId('');}} className={`rounded-xl px-3 py-2.5 text-sm font-black ${scheduled?'bg-blue-600 text-white':'text-zinc-400'}`}><CalendarClock className="mr-1 inline h-4 w-4"/>Agendar</button></div>
  {scheduled&&<label className="block rounded-2xl border border-blue-500/25 bg-blue-500/5 p-4"><span className="mb-2 flex items-center gap-2 text-xs font-black text-white"><Clock3 className="h-4 w-4 text-blue-300"/>Fecha y hora</span><input type="datetime-local" value={scheduledLocal} onChange={e=>setScheduledLocal(e.target.value)} className={`${inputClass} [color-scheme:dark]`}/></label>}
  <div className="grid gap-4 md:grid-cols-2"><AddressBox ref={originRef} label="1. Retiro" value={origin} onChange={setOrigin} suggestions={addressCache} origin/><AddressBox label="2. Destino" value={destination} onChange={setDestination} suggestions={['A convenir / Taxímetro',...fares.filter(f=>f.active).map(f=>f.name),...addressCache]}/></div>
  {fareMatch&&<div className="rounded-xl border border-emerald-500/25 bg-emerald-500/10 px-4 py-3 text-xs text-emerald-200"><Sparkles className="mr-2 inline h-4 w-4"/><strong>Tarifa automática:</strong> {fareMatch.name} · ${Math.round(fareMatch.fareAmount).toLocaleString('es-CL')}</div>}
  <div className="grid gap-3 md:grid-cols-2"><Field label="Pasajero" icon={UserRound}><input value={clientName} onChange={e=>setClientName(e.target.value)} className={inputClass}/></Field><Field label="Teléfono" icon={Phone}><input value={clientPhone} onChange={e=>setClientPhone(e.target.value)} placeholder="+56 9…" className={inputClass}/></Field><Field label="Forma de pago" icon={CircleDollarSign}><select value={payment} onChange={e=>setPayment(e.target.value as PaymentMethod)} className={inputClass}><option value="efectivo">Efectivo</option><option value="transferencia">Transferencia</option><option value="posnet_tarjeta">Tarjeta / POS</option><option value="cuenta_corriente">Cuenta corriente</option></select></Field><Field label="Cliente frecuente" icon={UserRound}><select value={clientId} onChange={e=>selectClient(e.target.value)} className={inputClass}><option value="">Cliente ocasional</option>{clients.map(c=><option key={c.id} value={c.id}>{c.name} · {c.phone}</option>)}</select></Field></div>
  <section className="rounded-2xl border border-zinc-800 bg-zinc-950/60 p-4"><div className="flex items-center justify-between"><div><h3 className="text-sm font-black text-white">3. Asignación</h3><p className="mt-0.5 text-xs text-zinc-500">Automático pondera cercanía, carreras del turno y prioridad recuperada.</p></div><span className="text-xs font-black text-emerald-300">{available.length} libres</span></div><div className="mt-3 flex max-h-36 flex-wrap gap-2 overflow-y-auto"><button type="button" onClick={()=>setDriverId('')} className={`rounded-xl border px-3 py-2 text-xs font-black ${driverId===''?'border-amber-300 bg-amber-400 text-zinc-950':'border-zinc-700 bg-zinc-900 text-zinc-300'}`}>Automático equitativo</button>{!scheduled&&available.map(d=><button key={d.id} type="button" onClick={()=>setDriverId(d.id)} className={`rounded-xl border px-3 py-2 text-xs font-bold ${driverId===d.id?'border-blue-400 bg-blue-600 text-white':'border-zinc-700 bg-zinc-900 text-zinc-300'}`}>{d.unitNumber} · {d.name.split(' ')[0]}</button>)}</div>{clientId&&blockedDriverIds.size>0&&<p className="mt-2 text-[10px] text-rose-300">{blockedDriverIds.size} móvil(es) excluido(s) por preferencia registrada del cliente.</p>}</section>
  <section className="grid gap-3 md:grid-cols-3"><Field label="Tipo vehículo" icon={Car}><select value={vehicleType} onChange={e=>setVehicleType(e.target.value as typeof vehicleType)} className={inputClass}><option value="standard">Estándar</option><option value="pet">Mascotas</option><option value="wheelchair">Accesible</option><option value="vip">VIP</option></select></Field><Field label="Distancia estimada" icon={Navigation}><input type="number" min=".5" step=".5" value={km} onChange={e=>setKm(Number(e.target.value))} className={inputClass}/></Field><Field label="Observación" icon={MessageSquareText}><input value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Esperar afuera…" className={inputClass}/></Field></section>
  {!fareMatch&&<div className="flex flex-wrap items-center gap-2 rounded-xl border border-zinc-800 bg-zinc-950/40 p-3"><button type="button" onClick={()=>setFixedFare(false)} className={`rounded-lg px-3 py-2 text-xs font-black ${!fixedFare?'bg-blue-600 text-white':'bg-zinc-900 text-zinc-400'}`}>Tarifa calculada</button><button type="button" onClick={()=>setFixedFare(true)} className={`rounded-lg px-3 py-2 text-xs font-black ${fixedFare?'bg-amber-400 text-zinc-950':'bg-zinc-900 text-zinc-400'}`}>Tarifa fija manual</button>{fixedFare&&<input type="number" min="0" step="500" value={fixedAmount} onChange={e=>setFixedAmount(Number(e.target.value))} className={`${inputClass} max-w-40`}/>}</div>}
  {error&&<div className="rounded-xl border border-rose-500/30 bg-rose-500/10 p-3 text-sm text-rose-200">{error}</div>}
  <footer className="flex flex-col-reverse gap-3 border-t border-zinc-800 pt-4 sm:flex-row sm:items-center sm:justify-between"><p className="text-sm text-zinc-500">Tarifa: <strong className="text-amber-300">${Math.round(calculated).toLocaleString('es-CL')}</strong></p><div className="flex gap-2"><button type="button" onClick={close} className="rounded-xl border border-zinc-700 bg-zinc-900 px-4 py-3 text-sm font-bold text-zinc-300">Cancelar</button><button disabled={submitting} className="flex items-center gap-2 rounded-xl bg-amber-400 px-6 py-3 text-sm font-black text-zinc-950 disabled:opacity-50"><Send className="h-4 w-4"/>{submitting?'Guardando…':scheduled?'Agendar carrera':'Despachar'}</button></div></footer>
 </form></div></div>;
};
const inputClass='w-full rounded-xl border border-zinc-700 bg-zinc-950 px-3 py-2.5 text-sm text-white outline-none placeholder:text-zinc-600 focus:border-amber-400';
const AddressBox=React.forwardRef<HTMLInputElement,{label:string;value:string;onChange:(v:string)=>void;suggestions:string[];origin?:boolean}>(({label,value,onChange,suggestions,origin},ref)=>{
 const[open,setOpen]=useState(false);
 const inputId=useId();
 const options=useMemo(()=>{const q=norm(value);const seen=new Set<string>();return suggestions.filter(item=>{const key=norm(item);if(!key||seen.has(key)){return false;}seen.add(key);return !q||key.includes(q)||q.includes(key);}).slice(0,10);},[suggestions,value]);
 return <div className={`relative rounded-2xl border p-4 ${origin?'border-emerald-500/25 bg-emerald-500/[.035]':'border-rose-500/25 bg-rose-500/[.035]'}`}><label htmlFor={inputId} className="mb-2 flex items-center gap-2 text-sm font-black text-white">{origin?<MapPin className="h-4 w-4 text-emerald-400"/>:<Navigation className="h-4 w-4 text-rose-400"/>}{label}</label><div className="relative"><input id={inputId} ref={ref} value={value} onFocus={()=>setOpen(true)} onClick={()=>setOpen(true)} onChange={e=>{onChange(e.target.value);setOpen(true);}} onBlur={()=>window.setTimeout(()=>setOpen(false),150)} placeholder={origin?'Dirección de retiro':'Destino o A convenir'} autoComplete="off" role="combobox" aria-expanded={open} aria-autocomplete="list" className={`${inputClass} pr-10 text-base`}/><button type="button" onMouseDown={e=>e.preventDefault()} onClick={()=>setOpen(v=>!v)} className="absolute inset-y-0 right-0 flex w-10 items-center justify-center text-zinc-400" aria-label={`Ver opciones de ${label.toLowerCase()}`}><ChevronDown className={`h-4 w-4 transition ${open?'rotate-180':''}`}/></button></div>{open&&<div role="listbox" className="absolute left-4 right-4 top-[88px] z-[80] max-h-56 overflow-y-auto rounded-xl border border-zinc-700 bg-zinc-950 p-1.5 shadow-2xl">{options.map(item=><button key={item} type="button" role="option" aria-selected={norm(item)===norm(value)} onMouseDown={e=>e.preventDefault()} onClick={()=>{onChange(item);setOpen(false);}} className="flex w-full items-start gap-2 rounded-lg px-3 py-2.5 text-left text-xs font-semibold text-zinc-200 hover:bg-zinc-800"><MapPin className="mt-0.5 h-3.5 w-3.5 shrink-0 text-zinc-500"/><span>{item}</span></button>)}{!options.length&&<p className="px-3 py-4 text-center text-[10px] text-zinc-500">Escribe una dirección nueva para continuar.</p>}</div>}<p className="mt-2 text-[9px] text-zinc-600">Presiona la flecha para ver direcciones frecuentes e históricas.</p></div>;
});AddressBox.displayName='AddressBox';
const Field=({label,icon:Icon,children}:{label:string;icon:React.ComponentType<{className?:string}>;children:React.ReactNode})=><label className="space-y-2"><span className="flex items-center gap-2 text-[10px] font-black uppercase tracking-wider text-zinc-500"><Icon className="h-4 w-4"/>{label}</span>{children}</label>;
