import React,{useEffect,useMemo,useState}from'react';
import{Loader2,LocateFixed,ShieldCheck,Radio,Smartphone,Power,RefreshCw}from'lucide-react';
import{useApp}from'../../context/AppContext';
import{isQueueConnected,loadDispatchQueue,setDriverOperationMode,setTraditionalDriverAvailability,subscribeDispatchQueue,type DispatchQueueItem}from'../../lib/dispatchPriorityRepository';

const activeStatuses=['assigned','en_route','arrived','in_progress'] as const;

export const DispatchPriorityBoard:React.FC=()=>{
 const{currentCompany,trips}=useApp();
 const[queue,setQueue]=useState<DispatchQueueItem[]>([]);
 const[busy,setBusy]=useState('');
 const[error,setError]=useState('');
 const load=async()=>{if(currentCompany.id==='network')return;try{setQueue(await loadDispatchQueue(currentCompany.id));setError('');}catch(err){setError(err instanceof Error?err.message:'No fue posible cargar la fila de prioridad.');}};
 useEffect(()=>{void load();if(currentCompany.id==='network')return;return subscribeDispatchQueue(currentCompany.id,()=>void load());},[currentCompany.id]);
 const ordered=useMemo(()=>[...queue].sort((a,b)=>a.queueOrder-b.queueOrder||a.unitNumber.localeCompare(b.unitNumber,'es',{numeric:true})),[queue]);
 const operational=useMemo(()=>ordered.filter(isQueueConnected),[ordered]);
 const activeByDriver=useMemo(()=>new Map(trips.filter(t=>t.driverId&&activeStatuses.includes(t.status as any)).map(t=>[t.driverId as string,t])),[trips]);
 const toggleMode=async(item:DispatchQueueItem)=>{const next=item.operationMode==='traditional'?'app':'traditional';setBusy(`mode:${item.driverId}`);setError('');try{await setDriverOperationMode(item.driverId,next);await load();}catch(err){setError(err instanceof Error?err.message:'No fue posible cambiar el modo del conductor.');}finally{setBusy('');}};
 const toggleTraditionalAvailability=async(item:DispatchQueueItem)=>{if(item.operationMode!=='traditional')return;const nextAvailable=item.status!=='available';setBusy(`presence:${item.driverId}`);setError('');try{await setTraditionalDriverAvailability(item.driverId,nextAvailable);await load();}catch(err){setError(err instanceof Error?err.message:'No fue posible actualizar la disponibilidad del móvil tradicional.');}finally{setBusy('');}};
 const locateDriver=(item:DispatchQueueItem)=>window.dispatchEvent(new CustomEvent('centralgo:locate-driver',{detail:{driverId:item.driverId,unitNumber:item.unitNumber,name:item.name}}));
 if(currentCompany.id==='network')return null;
 return <section className="cg-priority-board overflow-hidden rounded-[20px] border border-white/[0.07] bg-[linear-gradient(180deg,#111217_0%,#0b0c10_100%)] shadow-[0_24px_80px_rgba(0,0,0,.28)] xl:min-h-[650px]">
  <header className="border-b border-white/[0.06] bg-white/[0.015] px-3.5 py-3.5">
   <div className="flex items-start justify-between gap-2"><div className="min-w-0"><div className="flex items-center gap-2"><div className="grid h-7 w-7 shrink-0 place-items-center rounded-lg border border-cyan-400/20 bg-cyan-400/[0.08]"><ShieldCheck className="h-3.5 w-3.5 text-cyan-300"/></div><div><h2 className="text-sm font-black tracking-tight text-white">Fila de prioridad</h2><p className="mt-0.5 text-[9px] font-medium text-zinc-500">Orden real de móviles para recibir la próxima carrera</p></div></div></div><div className="flex shrink-0 items-center gap-2 rounded-xl border border-emerald-400/15 bg-emerald-400/[0.06] px-2.5 py-1.5"><span className="h-1.5 w-1.5 rounded-full bg-emerald-400"/><div><p className="text-[7px] font-black uppercase tracking-[.16em] text-emerald-300/80">Operativos</p><p className="text-sm font-black leading-none text-white">{operational.length}</p></div></div></div>
  </header>
  {error&&<div className="mx-3 mt-3 rounded-xl border border-rose-500/20 bg-rose-500/[0.08] px-3 py-2 text-[10px] font-medium text-rose-200">{error}</div>}
  <div className="p-3">
   <div className="mb-2 rounded-xl border border-cyan-400/10 bg-cyan-400/[0.035] px-3 py-2"><div className="flex items-center justify-between gap-2"><div><p className="text-[10px] font-black text-white">{ordered.length} móviles en la fila</p><p className="mt-0.5 text-[8px] leading-relaxed text-zinc-500">El Nº 1 tiene la mayor prioridad. App y radio respetan el mismo orden. Las carreras se gestionan en la Cola de despacho de la derecha.</p></div><button type="button" onClick={()=>void load()} className="grid h-7 w-7 shrink-0 place-items-center rounded-lg border border-white/[0.07] bg-white/[0.02] text-zinc-400" title="Actualizar fila"><RefreshCw className="h-3.5 w-3.5"/></button></div></div>
   <div className="max-h-[570px] space-y-1.5 overflow-y-auto pr-1 [scrollbar-color:#27272a_transparent] [scrollbar-width:thin]">
    {ordered.map((item,index)=>{const active=activeByDriver.get(item.driverId);const available=item.status==='available';const operationalNow=isQueueConnected(item);const traditional=item.operationMode==='traditional';const statusLabel=available?'Libre':item.status==='in_trip'?'En viaje':item.status==='en_route'?'En servicio':item.status==='paused'?'Pausa':'Fuera';return <article key={item.driverId} className={`rounded-xl border px-2.5 py-2.5 ${index===0&&available?'border-cyan-400/25 bg-cyan-400/[0.05]':'border-white/[0.06] bg-white/[0.018]'} ${!operationalNow?'opacity-65':''}`}>
     <div className="flex items-center gap-2"><div className={`grid h-8 w-8 shrink-0 place-items-center rounded-lg border text-[10px] font-black ${index===0&&available?'border-cyan-400/25 bg-cyan-400/10 text-cyan-200':'border-white/[0.07] bg-black/20 text-zinc-400'}`}>{index+1}</div><button type="button" onClick={()=>locateDriver(item)} className="min-w-0 flex-1 text-left"><div className="flex items-center gap-1"><span className="truncate text-[10px] font-black text-white">Móvil {item.unitNumber}</span>{traditional?<Radio className="h-3 w-3 shrink-0 text-amber-300"/>:<Smartphone className="h-3 w-3 shrink-0 text-cyan-300"/>}</div><p className="truncate text-[8px] text-zinc-500">{item.name||'Conductor'}{active?` · ${active.code}`:''}</p></button><button type="button" onClick={()=>locateDriver(item)} className="grid h-7 w-7 shrink-0 place-items-center rounded-lg border border-white/[0.06] text-zinc-400" title="Ubicar móvil"><LocateFixed className="h-3.5 w-3.5"/></button></div>
     <div className="mt-2 flex flex-wrap items-center gap-1.5 pl-10"><span className={`rounded-full border px-1.5 py-0.5 text-[7px] font-black ${available?'border-emerald-500/20 bg-emerald-500/10 text-emerald-300':'border-amber-500/20 bg-amber-500/10 text-amber-300'}`}>{statusLabel}</span><button type="button" disabled={Boolean(busy)||Boolean(active)} onClick={()=>void toggleMode(item)} className={`rounded-full border px-2 py-1 text-[7px] font-black ${traditional?'border-amber-400/20 bg-amber-400/10 text-amber-200':'border-cyan-400/20 bg-cyan-400/[0.07] text-cyan-200'} disabled:opacity-40`} title="Cambiar entre App y Tradicional">{busy===`mode:${item.driverId}`?<Loader2 className="h-3 w-3 animate-spin"/>:traditional?'Tradicional':'App'}</button>{traditional&&<button type="button" disabled={Boolean(busy)||Boolean(active)} onClick={()=>void toggleTraditionalAvailability(item)} className={`inline-flex items-center gap-1 rounded-full border px-2 py-1 text-[7px] font-black ${available?'border-emerald-400/20 bg-emerald-400/10 text-emerald-200':'border-zinc-600/30 bg-zinc-700/20 text-zinc-400'} disabled:opacity-40`} title={available?'Sacar temporalmente de la fila':'Reingresar a la fila'}>{busy===`presence:${item.driverId}`?<Loader2 className="h-3 w-3 animate-spin"/>:<Power className="h-3 w-3"/>}{available?'En fila':'Activar'}</button>}</div>
    </article>})}
    {!ordered.length&&<div className="rounded-xl border border-dashed border-white/[0.07] bg-white/[0.01] px-3 py-12 text-center"><p className="text-[11px] font-bold text-zinc-400">Sin móviles en prioridad</p><p className="mt-1 text-[9px] text-zinc-600">Los móviles operativos aparecerán aquí según su posición real.</p></div>}
   </div>
  </div>
 </section>;
};