import React,{useEffect,useMemo,useState}from'react';
import{Power,Radio,RefreshCw,Search,Smartphone,Wifi,WifiOff}from'lucide-react';
import{useApp}from'../../context/AppContext';
import{requireSupabase}from'../../lib/supabase';

type ControlRow={id:string;operationMode:'app'|'traditional';serviceEnabled:boolean;};

export const DriverDailyServicePanel:React.FC<{companyId:string}>=({companyId})=>{
 const{drivers}=useApp();
 const[controls,setControls]=useState<Record<string,ControlRow>>({});
 const[search,setSearch]=useState('');
 const[busyId,setBusyId]=useState<string|null>(null);
 const[error,setError]=useState('');
 const[notice,setNotice]=useState('');
 const[loading,setLoading]=useState(false);
 const load=async()=>{if(!companyId||companyId==='network')return;setLoading(true);try{const{data,error:e}=await requireSupabase().from('drivers').select('id,operation_mode,service_enabled').eq('company_id',companyId).order('unit_number');if(e)throw e;const next:Record<string,ControlRow>={};for(const r of data??[])next[r.id]={id:r.id,operationMode:(r.operation_mode??'app') as 'app'|'traditional',serviceEnabled:r.service_enabled??true};setControls(next);}catch(e){setError(e instanceof Error?e.message:'No fue posible cargar el control de turnos.');}finally{setLoading(false);}};
 useEffect(()=>{void load();},[companyId,drivers.length]);
 const rows=useMemo(()=>drivers.filter(d=>{const q=search.trim().toLowerCase();return!q||`${d.unitNumber} ${d.name}`.toLowerCase().includes(q);}).sort((a,b)=>a.unitNumber.localeCompare(b.unitNumber,'es',{numeric:true})),[drivers,search]);
 const change=async(driverId:string,enabled:boolean,mode:'app'|'traditional')=>{setBusyId(driverId);setError('');setNotice('');try{const{error:e}=await requireSupabase().rpc('centralgo_operator_set_driver_daily_service',{p_driver_id:driverId,p_enabled:enabled,p_mode:mode});if(e)throw e;setControls(c=>({...c,[driverId]:{id:driverId,operationMode:mode,serviceEnabled:enabled}}));const d=drivers.find(x=>x.id===driverId);setNotice(`${d?.unitNumber??'Móvil'}: ${mode==='traditional'?(enabled?'turno manual iniciado':'turno manual finalizado'):(enabled?'habilitado para trabajar con App':'suspendido de la operación')}.`);}catch(e){setError(e instanceof Error?e.message:'No fue posible cambiar el turno.');}finally{setBusyId(null);}};
 if(companyId==='network')return null;
 return <section className="rounded-2xl border border-cyan-500/20 bg-[#0d0d0f] p-4 shadow-xl shadow-black/20">
  <div className="flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between"><div><div className="flex items-center gap-2"><Power className="h-5 w-5 text-cyan-300"/><h2 className="text-base font-black text-white">Conductores trabajando hoy</h2></div><p className="mt-1 max-w-3xl text-xs leading-relaxed text-zinc-400">Los móviles con App entran a la fila cuando están conectados. Los móviles tradicionales se incorporan y se retiran manualmente desde aquí. Registrar un conductor no significa que esté trabajando.</p></div><button onClick={()=>void load()} disabled={loading} className="flex items-center justify-center gap-2 rounded-xl border border-zinc-700 bg-zinc-900 px-3 py-2 text-xs font-bold text-zinc-300 disabled:opacity-50"><RefreshCw className={`h-3.5 w-3.5 ${loading?'animate-spin':''}`}/>Actualizar</button></div>
  <div className="mt-3 relative max-w-md"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-zinc-500"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar móvil o conductor…" className="w-full rounded-xl border border-zinc-800 bg-zinc-950 py-2.5 pl-9 pr-3 text-xs text-white outline-none focus:border-cyan-500"/></div>
  {notice&&<p className="mt-3 rounded-xl border border-emerald-500/25 bg-emerald-500/10 px-3 py-2 text-xs font-bold text-emerald-200">{notice}</p>}{error&&<p className="mt-3 rounded-xl border border-rose-500/25 bg-rose-500/10 px-3 py-2 text-xs font-bold text-rose-200">{error}</p>}
  <div className="mt-3 grid gap-2 md:grid-cols-2 xl:grid-cols-3">{rows.map(d=>{const c=controls[d.id]??{id:d.id,operationMode:'app' as const,serviceEnabled:true};const appOnline=c.operationMode==='app'&&c.serviceEnabled&&d.status!=='offline';const active=c.operationMode==='traditional'?c.serviceEnabled:appOnline;return <article key={d.id} className={`rounded-xl border p-3 ${active?'border-emerald-500/25 bg-emerald-500/[.055]':'border-zinc-800 bg-zinc-950/55'}`}><div className="flex items-start justify-between gap-2"><div><p className="text-sm font-black text-white">Móvil {d.unitNumber}</p><p className="text-xs text-zinc-400">{d.name}</p></div><span className={`flex items-center gap-1 rounded-full px-2 py-1 text-[9px] font-black ${active?'bg-emerald-500/15 text-emerald-300':'bg-zinc-800 text-zinc-500'}`}>{active?<Wifi className="h-3 w-3"/>:<WifiOff className="h-3 w-3"/>}{c.operationMode==='traditional'?(c.serviceEnabled?'EN FILA':'FUERA DE TURNO'):(appOnline?'APP EN LÍNEA':c.serviceEnabled?'ESPERANDO APP':'SUSPENDIDO')}</span></div><div className="mt-3 grid grid-cols-2 gap-1 rounded-lg border border-zinc-800 bg-zinc-950 p-1"><button disabled={busyId===d.id} onClick={()=>void change(d.id,c.serviceEnabled,'app')} className={`flex items-center justify-center gap-1 rounded-md px-2 py-2 text-[10px] font-black ${c.operationMode==='app'?'bg-blue-600 text-white':'text-zinc-500 hover:text-white'}`}><Smartphone className="h-3.5 w-3.5"/>App</button><button disabled={busyId===d.id} onClick={()=>void change(d.id,false,'traditional')} className={`flex items-center justify-center gap-1 rounded-md px-2 py-2 text-[10px] font-black ${c.operationMode==='traditional'?'bg-amber-400 text-zinc-950':'text-zinc-500 hover:text-white'}`}><Radio className="h-3.5 w-3.5"/>Manual</button></div><button disabled={busyId===d.id} onClick={()=>void change(d.id,!c.serviceEnabled,c.operationMode)} className={`mt-2 w-full rounded-lg px-3 py-2 text-xs font-black disabled:opacity-50 ${c.serviceEnabled?'border border-rose-500/25 bg-rose-500/10 text-rose-200':'bg-emerald-500 text-emerald-950'}`}>{busyId===d.id?'Guardando…':c.operationMode==='traditional'?(c.serviceEnabled?'Finalizar turno':'Iniciar turno'):(c.serviceEnabled?'Suspender de la operación':'Habilitar App')}</button>{c.operationMode==='app'&&c.serviceEnabled&&d.status==='offline'&&<p className="mt-2 text-[9px] leading-relaxed text-zinc-600">Habilitado, pero no entra a la fila hasta que su aplicación vuelva a conectarse.</p>}{c.operationMode==='traditional'&&c.serviceEnabled&&<p className="mt-2 text-[9px] leading-relaxed text-amber-200/70">Móvil sin GPS: participa en la fila manual, no en el despacho automático por cercanía.</p>}</article>;})}</div>
 </section>;
};
