import React,{useEffect,useMemo,useState}from'react';
import{CalendarDays,Download,FileText,History,Loader2,Search,ShieldCheck}from'lucide-react';
import{useApp}from'../../context/AppContext';
import{loadOperationalTripHistory}from'../../lib/operationsHistoryRepository';
import{exportTableToExcel,printTableAsPdf}from'../../lib/exportUtils';
import type{Trip}from'../../types';
import{TRIP_STATUS_LABELS}from'../../lib/labels';

const isoDaysAgo=(days:number)=>{const d=new Date();d.setDate(d.getDate()-days);d.setHours(0,0,0,0);return d.toISOString();};
const paymentLabel:Record<string,string>={efectivo:'Efectivo',transferencia:'Transferencia',posnet_tarjeta:'Tarjeta/POS',cuenta_corriente:'Cuenta corriente'};

export const HistoryModule:React.FC=()=>{
 const{currentCompany,drivers,vehicles,auditLogs}=useApp();
 const[trips,setTrips]=useState<Trip[]>([]),[loading,setLoading]=useState(false),[error,setError]=useState('');
 const[search,setSearch]=useState(''),[driverId,setDriverId]=useState(''),[vehicleId,setVehicleId]=useState(''),[status,setStatus]=useState('all'),[range,setRange]=useState('30');
 const[tab,setTab]=useState<'trips'|'audit'>('trips');
 const load=async()=>{setLoading(true);setError('');try{const days=Number(range);setTrips(await loadOperationalTripHistory(currentCompany.id,{from:days?isoDaysAgo(days):undefined,driverId:driverId||undefined,vehicleId:vehicleId||undefined,status,search}));}catch(e){setError(e instanceof Error?e.message:'No fue posible cargar el historial.');}finally{setLoading(false);}};
 useEffect(()=>{if(currentCompany.id!=='network')void load();},[currentCompany.id,driverId,vehicleId,status,range]);
 const visible=useMemo(()=>{const q=search.trim().toLowerCase();return !q?trips:trips.filter(t=>[t.code,t.clientName,t.clientPhone,t.origin.address,t.destination.address,t.driverName??'',t.driverUnitNumber??'',t.vehiclePlate??'',t.operatorName].join(' ').toLowerCase().includes(q));},[trips,search]);
 const rows=visible.map(t=>[new Date(t.createdAt).toLocaleString('es-CL'),t.code,t.clientName,t.clientPhone,t.origin.address,t.destination.address,t.driverName??'Sin conductor',t.driverUnitNumber??'',t.vehiclePlate??'',TRIP_STATUS_LABELS[t.status],paymentLabel[t.paymentMethod]??t.paymentMethod,t.finalFare??t.estimatedFare,t.cancelReason??'']);
 const headers=['Fecha','Código','Cliente','Teléfono','Origen','Destino','Chofer','Móvil','Patente','Estado','Pago','Tarifa','Cancelación'];
 return <div className="space-y-5">
  <div className="flex flex-col gap-3 lg:flex-row lg:items-end lg:justify-between"><div><h1 className="flex items-center gap-2 text-2xl font-extrabold text-white"><History className="h-6 w-6 text-blue-500"/>Historial operacional</h1><p className="mt-1 text-xs text-zinc-400">Archivo de carreras, conductores y vehículos con consulta histórica de hasta 5 años y exportación.</p></div><div className="flex gap-2"><button onClick={()=>exportTableToExcel(`central-go-${currentCompany.code}-historial.xls`,headers,rows)} disabled={!visible.length} className="flex items-center gap-2 rounded-xl border border-emerald-500/30 bg-emerald-500/10 px-3 py-2 text-xs font-black text-emerald-300 disabled:opacity-30"><Download className="h-4 w-4"/>Excel</button><button onClick={()=>printTableAsPdf(`Historial ${currentCompany.name}`,headers,rows)} disabled={!visible.length} className="flex items-center gap-2 rounded-xl border border-rose-500/30 bg-rose-500/10 px-3 py-2 text-xs font-black text-rose-300 disabled:opacity-30"><FileText className="h-4 w-4"/>PDF</button></div></div>
  <div className="flex gap-1 rounded-xl border border-zinc-800 bg-[#0d0d0f] p-1"><button onClick={()=>setTab('trips')} className={`flex-1 rounded-lg px-3 py-2 text-xs font-black ${tab==='trips'?'bg-blue-600 text-white':'text-zinc-500'}`}>Carreras y pedidos</button><button onClick={()=>setTab('audit')} className={`flex-1 rounded-lg px-3 py-2 text-xs font-black ${tab==='audit'?'bg-zinc-800 text-white':'text-zinc-500'}`}>Auditoría</button></div>
  {tab==='trips'?<>
   <section className="grid gap-2 rounded-2xl border border-zinc-800 bg-[#0d0d0f] p-3 md:grid-cols-2 xl:grid-cols-[1.5fr_repeat(4,1fr)_auto]"><label className="relative"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-zinc-600"/><input value={search} onChange={e=>setSearch(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')void load();}} placeholder="Código, teléfono, dirección, móvil, patente…" className="w-full rounded-xl border border-zinc-800 bg-zinc-950 py-2.5 pl-9 pr-3 text-xs text-white outline-none focus:border-blue-500"/></label><select value={driverId} onChange={e=>setDriverId(e.target.value)} className="rounded-xl border border-zinc-800 bg-zinc-950 px-3 py-2.5 text-xs text-white"><option value="">Todos los choferes</option>{drivers.map(d=><option key={d.id} value={d.id}>{d.unitNumber} · {d.name}</option>)}</select><select value={vehicleId} onChange={e=>setVehicleId(e.target.value)} className="rounded-xl border border-zinc-800 bg-zinc-950 px-3 py-2.5 text-xs text-white"><option value="">Todos los vehículos</option>{vehicles.map(v=><option key={v.id} value={v.id}>{v.unitNumber} · {v.licensePlate}</option>)}</select><select value={status} onChange={e=>setStatus(e.target.value)} className="rounded-xl border border-zinc-800 bg-zinc-950 px-3 py-2.5 text-xs text-white"><option value="all">Todos los estados</option><option value="completed">Completadas</option><option value="cancelled">Canceladas</option><option value="pending">Pendientes</option><option value="assigned">Asignadas</option></select><select value={range} onChange={e=>setRange(e.target.value)} className="rounded-xl border border-zinc-800 bg-zinc-950 px-3 py-2.5 text-xs text-white"><option value="1">Hoy</option><option value="7">7 días</option><option value="30">30 días</option><option value="365">1 año</option><option value="1825">5 años</option><option value="0">Todo el historial</option></select><button onClick={()=>void load()} className="rounded-xl bg-blue-600 px-4 py-2.5 text-xs font-black text-white">Buscar</button></section>
   {error&&<div className="rounded-xl border border-rose-500/30 bg-rose-500/10 p-3 text-xs text-rose-200">{error}</div>}
   <section className="overflow-hidden rounded-2xl border border-zinc-800 bg-[#0d0d0f]"><div className="flex items-center justify-between border-b border-zinc-800 px-4 py-3"><div><p className="text-xs font-black text-white">{visible.length.toLocaleString('es-CL')} registros</p><p className="text-[9px] text-zinc-600">El vehículo queda guardado como fotografía histórica al momento de la asignación.</p></div>{loading&&<Loader2 className="h-4 w-4 animate-spin text-blue-400"/>}</div><div className="max-h-[64vh] overflow-auto"><table className="w-full min-w-[1250px] text-left text-[10px]"><thead className="sticky top-0 bg-zinc-950 text-zinc-500"><tr>{headers.slice(0,12).map(h=><th key={h} className="px-3 py-2 font-black uppercase">{h}</th>)}</tr></thead><tbody className="divide-y divide-zinc-900">{visible.map(t=><tr key={t.id} className="hover:bg-zinc-900/50"><td className="px-3 py-2 text-zinc-400">{new Date(t.createdAt).toLocaleString('es-CL')}</td><td className="px-3 py-2 font-mono font-bold text-blue-300">{t.code}</td><td className="px-3 py-2 text-white">{t.clientName}<span className="block text-zinc-600">{t.clientPhone}</span></td><td className="px-3 py-2 max-w-52 truncate text-zinc-300">{t.origin.address}</td><td className="px-3 py-2 max-w-52 truncate text-zinc-500">{t.destination.address}</td><td className="px-3 py-2 text-zinc-300">{t.driverName??'—'}</td><td className="px-3 py-2 font-bold text-amber-300">{t.driverUnitNumber??'—'}</td><td className="px-3 py-2 text-zinc-300">{t.vehiclePlate??'—'}</td><td className="px-3 py-2 text-zinc-300">{TRIP_STATUS_LABELS[t.status]}</td><td className="px-3 py-2 text-zinc-400">{paymentLabel[t.paymentMethod]??t.paymentMethod}</td><td className="px-3 py-2 font-bold text-emerald-300">${Math.round(t.finalFare??t.estimatedFare).toLocaleString('es-CL')}</td><td className="px-3 py-2 text-zinc-500">{t.cancelReason??'—'}</td></tr>)}</tbody></table></div></section>
  </>:<section className="overflow-hidden rounded-2xl border border-zinc-800 bg-[#0d0d0f]"><div className="border-b border-zinc-800 p-4"><p className="flex items-center gap-2 text-sm font-black text-white"><ShieldCheck className="h-4 w-4 text-emerald-400"/>Auditoría de acciones</p></div><div className="max-h-[65vh] overflow-auto"><table className="w-full min-w-[850px] text-left text-xs"><thead className="sticky top-0 bg-zinc-950 text-[9px] uppercase text-zinc-500"><tr><th className="p-3">Fecha</th><th className="p-3">Usuario</th><th className="p-3">Rol</th><th className="p-3">Acción</th><th className="p-3">Descripción</th></tr></thead><tbody className="divide-y divide-zinc-900">{auditLogs.map(log=><tr key={log.id}><td className="p-3 text-zinc-500">{new Date(log.timestamp).toLocaleString('es-CL')}</td><td className="p-3 font-bold text-white">{log.userName}</td><td className="p-3 text-blue-300">{log.userRole}</td><td className="p-3 font-mono text-emerald-300">{log.action}</td><td className="p-3 text-zinc-300">{log.description}</td></tr>)}</tbody></table></div></section>}
 </div>;
};
