import React,{useState}from'react';
import{BookOpen,Building2,Camera,Download,Loader2,Shield,User}from'lucide-react';
import{useApp}from'../../context/AppContext';
import{useAuth}from'../../context/AuthContext';
import{uploadCompanyLogo,uploadOwnAvatar}from'../../lib/profileMediaRepository';

export const ProfileModule:React.FC=()=>{
 const{currentUser,currentCompany,currentRole}=useApp();const{refreshIdentity}=useAuth();const[busy,setBusy]=useState<'avatar'|'company'|null>(null),[error,setError]=useState('');
 const changeAvatar=async(file?:File)=>{if(!file)return;setBusy('avatar');setError('');try{await uploadOwnAvatar(currentUser.id,file);await refreshIdentity();}catch(err){setError(err instanceof Error?err.message:'No fue posible guardar la fotografía.');}finally{setBusy(null);}};
 const changeCompany=async(file?:File)=>{if(!file)return;setBusy('company');setError('');try{await uploadCompanyLogo(currentCompany.id,file);await refreshIdentity();}catch(err){setError(err instanceof Error?err.message:'No fue posible guardar la imagen de la central.');}finally{setBusy(null);}};
 return <div className="max-w-3xl space-y-6"><div><h1 className="flex items-center gap-2 text-2xl font-extrabold text-white"><User className="h-6 w-6 text-zinc-300"/>Perfil e identidad</h1><p className="mt-1 text-xs text-zinc-400">Fotografías visibles para una operación reconocible y profesional.</p></div>
 <section className="cg-card p-6"><div className="flex flex-col gap-5 sm:flex-row sm:items-center"><Photo src={currentUser.avatarUrl} fallback={currentUser.name[0]}/><div className="flex-1"><h2 className="text-lg font-black text-white">{currentUser.name}</h2><p className="text-xs text-zinc-400">{currentUser.email}</p><p className="mt-1 text-[9px] font-black uppercase tracking-wider text-zinc-500">{currentUser.role}</p><label className="action-secondary mt-4 cursor-pointer"><Camera className="h-4 w-4"/>{busy==='avatar'?'Subiendo…':'Cambiar mi foto'}<input type="file" accept="image/jpeg,image/png,image/webp" className="hidden" disabled={Boolean(busy)} onChange={e=>void changeAvatar(e.target.files?.[0])}/></label></div></div></section>
 {currentRole==='company_admin'&&<><section className="cg-card p-6"><div className="flex flex-col gap-5 sm:flex-row sm:items-center"><Photo src={currentCompany.logoUrl} fallback={<Building2 className="h-8 w-8"/>}/><div className="flex-1"><h2 className="text-lg font-black text-white">{currentCompany.name}</h2><p className="text-xs text-zinc-400">Foto oficial de la central para conductores y paneles.</p><label className="action-secondary mt-4 cursor-pointer"><Camera className="h-4 w-4"/>{busy==='company'?'Subiendo…':'Cambiar foto de central'}<input type="file" accept="image/jpeg,image/png,image/webp" className="hidden" disabled={Boolean(busy)} onChange={e=>void changeCompany(e.target.files?.[0])}/></label></div></div></section>
 <section className="relative overflow-hidden rounded-2xl border border-blue-500/25 bg-gradient-to-br from-blue-950/35 via-[#0d0d0f] to-cyan-950/20 p-6 shadow-xl"><div className="absolute -right-10 -top-12 h-36 w-36 rounded-full bg-blue-500/10 blur-2xl"/><div className="relative flex flex-col gap-5 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-start gap-4"><div className="rounded-2xl border border-blue-400/25 bg-blue-500/10 p-3 text-blue-300"><BookOpen className="h-6 w-6"/></div><div><p className="text-[10px] font-black uppercase tracking-[.18em] text-cyan-300">Guía oficial de operación</p><h2 className="mt-1 text-base font-black text-white">Manual de uso de Central GO</h2><p className="mt-1 max-w-lg text-xs leading-relaxed text-zinc-400">Configuración de la central, consola de despacho, conductores, vehículos, GPS, seguridad, reportes, solución de problemas y checklist diario.</p></div></div><a href="/docs/manual-central-go-centrales.pdf" download="Central_GO_Manual_Centrales.pdf" className="action-primary shrink-0"><Download className="h-4 w-4"/>Descargar PDF</a></div></section></>}
 {error&&<div className="rounded-xl border border-rose-500/30 bg-rose-500/10 p-3 text-sm text-rose-200">{error}</div>}{busy&&<div className="flex items-center gap-2 text-xs text-zinc-400"><Loader2 className="h-4 w-4 animate-spin"/>Optimizando y guardando imagen…</div>}
 <div className="flex items-center gap-2 text-[10px] text-zinc-500"><Shield className="h-4 w-4"/>JPG, PNG o WebP · máximo 5 MB.</div></div>;
};
const Photo=({src,fallback}:{src?:string;fallback:React.ReactNode})=><div className="grid h-24 w-24 shrink-0 place-items-center overflow-hidden rounded-3xl border border-zinc-700 bg-zinc-900 text-3xl font-black text-zinc-300 shadow-xl">{src?<img src={src} alt="Foto de perfil" className="h-full w-full object-cover"/>:fallback}</div>;
