import React,{useEffect,useMemo,useState}from'react';
import{BarChart3,Clock3,Download,FileText,PhoneCall,Plus,Route,Users,X}from'lucide-react';
import{Bar,BarChart,CartesianGrid,Legend,Line,LineChart,ResponsiveContainer,Tooltip,XAxis,YAxis}from'recharts';
import{useApp}from'../../context/AppContext';
import{addCallLog,loadCallLogs,loadCompanyShiftAnalytics,type CompanyDriverMetric}from'../../lib/operationalIntelligenceRepository';
import{exportTableToExcel,printAnalyticsReport}from'../../lib/exportUtils';
import type{CallLog,Trip}from'../../types';

const paymentLabel:Record<string,string>={efectivo:'Efectivo',transferencia:'Transferencia',posnet_tarjeta:'Tarjeta/POS',cuenta_corriente:'Cuenta corriente'};
const localInput=(date:Date)=>new Date(date.getTime()-date.getTimezoneOffset()*60000).toISOString().slice(0,16);
const startToday=()=>{const d=new Date();d.setHours(0,0,0,0);return localInput(d);};
const duration=(seconds:number)=>{const min=Math.round(seconds/60);return min>=60?`${Math.floor(min/60)}h ${String(min%60).padStart(2,'0')}m`:`${min} min`;};
const iso=(value:string)=>new Date(value).toISOString();

export const ReportsModule:React.FC=()=>{
 const{currentCompany}=useApp();
 const[from,setFrom]=useState(startToday),[to,setTo]=useState(()=>localInput(new Date())),[applied,setApplied]=useState(()=>({from:iso(startToday()),to:new Date().toISOString()}));
 const[trips,setTrips]=useState<Trip[]>([]),[driverMetrics,setDriverMetrics]=useState<CompanyDriverMetric[]>([]),[calls,setCalls]=useState<CallLog[]>([]),[loading,setLoading]=useState(false),[error,setError]=useState('');
 const[callOpen,setCallOpen]=useState(false),[callPhone,setCallPhone]=useState(''),[callName,setCallName]=useState(''),[callOutcome,setCallOutcome]=useState<CallLog['outcome']>('pedido'),[callNotes,setCallNotes]=useState('');
 const reload=async(range=applied)=>{if(currentCompany.id==='network')return;setLoading(true);setError('');try{const[data,callRows]=await Promise.all([loadCompanyShiftAnalytics(currentCompany.id,range.from,range.to),loadCallLogs(currentCompany.id,range.from,range.to)]);setTrips(data.trips);setDriverMetrics(data.drivers);setCalls(callRows);}catch(err){setError(err instanceof Error?err.message:'No fue posible cargar las métricas.');}finally{setLoading(false);}};
 useEffect(()=>{void reload();},[currentCompany.id,applied.from,applied.to]);
 const applyRange=()=>{const next={from:iso(from),to:iso(to)};if(new Date(next.to)<=new Date(next.from)){setError('La hora final debe ser posterior a la inicial.');return;}setApplied(next);};
 const stats=useMemo(()=>{const completed=trips.filter(t=>t.status==='completed'),cancelled=trips.filter(t=>t.status==='cancelled'),gross=completed.reduce((s,t)=>s+(t.finalFare??t.estimatedFare??0),0),driving=driverMetrics.reduce((s,d)=>s+d.drivingSeconds,0),connected=driverMetrics.reduce((s,d)=>s+d.connectedSeconds,0),opportunities=completed.length+cancelled.length+driverMetrics.reduce((s,d)=>s+d.rejected,0);return{completed,cancelled,gross,driving,connected,effectiveness:opportunities?Math.round(completed.length/opportunities*100):0};},[trips,driverMetrics]);
 const hourly=useMemo(()=>{const map=new Map<string,{label:string;trips:number;amount:number}>();trips.forEach(t=>{const d=new Date(t.createdAt),key=`${d.toISOString().slice(0,10)}-${d.getHours()}`,label=d.toLocaleTimeString('es-CL',{hour:'2-digit',minute:'2-digit'}).replace(':00',' h'),item=map.get(key)??{label,trips:0,amount:0};item.trips++;if(t.status==='completed')item.amount+=t.finalFare??t.estimatedFare??0;map.set(key,item);});return[...map.values()];},[trips]);
 const operationHeaders=['Registro','Código','Cliente','Teléfono','Origen','Destino','Móvil','Conductor','Operadora','Inicio viaje','Fin','Duración','Estado','Pago','Monto'];
 const operationRows=trips.map(t=>[new Date(t.createdAt).toLocaleString('es-CL'),t.code,t.clientName,t.clientPhone,t.origin.address,t.destination.address,t.driverUnitNumber??'—',t.driverName??'Sin asignar',t.operatorName,t.startedAt?new Date(t.startedAt).toLocaleString('es-CL'):'—',t.completedAt?new Date(t.completedAt).toLocaleString('es-CL'):'—',t.startedAt&&t.completedAt?duration((new Date(t.completedAt).getTime()-new Date(t.startedAt).getTime())/1000):'—',t.status,paymentLabel[t.paymentMethod]??t.paymentMethod,t.finalFare??t.estimatedFare]);
 const driverHeaders=['Móvil','Conductor','Conectado','Conducción','Carreras','Efectividad','Rechazos','Km servicio','Monto'];
 const driverRows=driverMetrics.map(d=>[d.unitNumber,d.name,duration(d.connectedSeconds),duration(d.drivingSeconds),d.tripsCompleted,`${d.effectiveness}%`,d.rejected,d.serviceKm.toFixed(1),Math.round(d.earnings)]);
 const period=`${new Date(applied.from).toLocaleString('es-CL')} — ${new Date(applied.to).toLocaleString('es-CL')}`;
 const exportPdf=()=>printAnalyticsReport({title:`Analítica de turno · ${currentCompany.name}`,period,kpis:[{label:'Carreras',value:String(trips.length)},{label:'Completadas',value:String(stats.completed.length)},{label:'Efectividad',value:`${stats.effectiveness}%`},{label:'Conducción',value:duration(stats.driving)},{label:'Facturación',value:`$${Math.round(stats.gross).toLocaleString('es-CL')}`}],series:hourly,driverHeaders,driverRows,operationHeaders,operationRows});
 const submitCall=async(e:React.FormEvent)=>{e.preventDefault();setError('');try{await addCallLog(currentCompany.id,{clientName:callName,phone:callPhone,outcome:callOutcome,notes:callNotes});setCallOpen(false);setCallPhone('');setCallName('');setCallNotes('');await reload();}catch(err){setError(err instanceof Error?err.message:'No fue posible registrar la llamada.');}};
 return <div className="space-y-5"><div className="flex flex-col gap-3 xl:flex-row xl:items-end xl:justify-between"><div><h1 className="flex items-center gap-2 text-2xl font-extrabold text-white"><BarChart3 className="h-6 w-6 text-zinc-300"/>Analítica de operación</h1><p className="mt-1 text-xs text-zinc-400">Turno completo, rendimiento por conductor y registro de cada operación.</p></div><div className="flex flex-wrap gap-2"><button onClick={()=>setCallOpen(true)} className="action-secondary"><PhoneCall className="h-4 w-4"/>Llamada</button><button disabled={!trips.length} onClick={()=>exportTableToExcel(`central-go-${currentCompany.code}-turno.xls`,operationHeaders,operationRows)} className="action-secondary"><Download className="h-4 w-4"/>Excel</button><button disabled={!trips.length} onClick={exportPdf} className="action-primary"><FileText className="h-4 w-4"/>PDF con gráficas</button></div></div>
 <section className="cg-card grid gap-3 p-4 lg:grid-cols-[1fr_1fr_auto]"><label className="field-label">Desde<input type="datetime-local" value={from} onChange={e=>setFrom(e.target.value)} className="field-input"/></label><label className="field-label">Hasta<input type="datetime-local" value={to} onChange={e=>setTo(e.target.value)} className="field-input"/></label><button onClick={applyRange} disabled={loading} className="action-primary self-end"><Clock3 className="h-4 w-4"/>{loading?'Calculando…':'Aplicar horario'}</button></section>
 {error&&<div className="rounded-xl border border-rose-500/30 bg-rose-500/10 p-3 text-xs text-rose-200">{error}</div>}
 <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-6"><Metric label="Carreras" value={String(trips.length)} detail={`${stats.completed.length} completadas`} icon={Route}/><Metric label="Efectividad" value={`${stats.effectiveness}%`} detail={`${stats.cancelled.length} canceladas`} icon={BarChart3}/><Metric label="Facturación" value={`$${Math.round(stats.gross).toLocaleString('es-CL')}`} detail="turno seleccionado" icon={BarChart3}/><Metric label="Conducción" value={duration(stats.driving)} detail="tiempo en carrera" icon={Clock3}/><Metric label="Conexión" value={duration(stats.connected)} detail="suma de conductores" icon={Users}/><Metric label="Llamadas" value={String(calls.length)} detail="en el horario" icon={PhoneCall}/></div>
 <div className="grid gap-5 xl:grid-cols-2"><ChartCard title="Carreras y montos por hora"><ResponsiveContainer width="100%" height={280}><BarChart data={hourly}><CartesianGrid strokeDasharray="3 3" stroke="rgba(128,128,128,.18)"/><XAxis dataKey="label" tick={{fontSize:10,fill:'#9ca3af'}}/><YAxis yAxisId="left" tick={{fontSize:10,fill:'#9ca3af'}}/><YAxis yAxisId="right" orientation="right" tick={{fontSize:10,fill:'#9ca3af'}}/><Tooltip/><Legend/><Bar yAxisId="left" dataKey="trips" name="Carreras" fill="#d4d7dc" radius={[5,5,0,0]}/><Bar yAxisId="right" dataKey="amount" name="Monto" fill="#555b65" radius={[5,5,0,0]}/></BarChart></ResponsiveContainer></ChartCard><ChartCard title="Efectividad por conductor"><ResponsiveContainer width="100%" height={280}><LineChart data={driverMetrics}><CartesianGrid strokeDasharray="3 3" stroke="rgba(128,128,128,.18)"/><XAxis dataKey="unitNumber" tick={{fontSize:10,fill:'#9ca3af'}}/><YAxis domain={[0,100]} tick={{fontSize:10,fill:'#9ca3af'}}/><Tooltip/><Line type="monotone" dataKey="effectiveness" name="Efectividad %" stroke="#e5e7eb" strokeWidth={3} dot={{r:4,fill:'#71717a'}}/></LineChart></ResponsiveContainer></ChartCard></div>
 <section className="cg-card overflow-hidden"><div className="border-b border-zinc-800 p-4"><h2 className="text-sm font-black text-white">Rendimiento de conductores</h2><p className="mt-1 text-[10px] text-zinc-500">Conexión, conducción, productividad y efectividad del horario seleccionado.</p></div><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-xs"><thead className="bg-zinc-950 text-[9px] uppercase text-zinc-500"><tr>{driverHeaders.map(h=><th key={h} className="p-3">{h}</th>)}</tr></thead><tbody className="divide-y divide-zinc-800">{driverRows.map((row,i)=><tr key={driverMetrics[i]?.driverId}>{row.map((v,j)=><td key={j} className="p-3 text-zinc-300">{v}</td>)}</tr>)}</tbody></table></div></section>
 {callOpen&&<div className="fixed inset-0 z-[120] flex items-center justify-center bg-black/85 p-4 backdrop-blur-md"><form onSubmit={submitCall} className="cg-card w-full max-w-md p-6"><div className="flex items-center justify-between"><div><h2 className="text-lg font-black text-white">Registrar llamada</h2><p className="mt-1 text-xs text-zinc-500">Consulta, pedido, cancelación o reclamo.</p></div><button type="button" onClick={()=>setCallOpen(false)} className="p-2 text-zinc-500"><X className="h-4 w-4"/></button></div><div className="mt-5 space-y-3"><input required value={callPhone} onChange={e=>setCallPhone(e.target.value)} placeholder="Teléfono" className="field-input"/><input value={callName} onChange={e=>setCallName(e.target.value)} placeholder="Cliente (opcional)" className="field-input"/><select value={callOutcome} onChange={e=>setCallOutcome(e.target.value as CallLog['outcome'])} className="field-input"><option value="pedido">Pedido</option><option value="consulta">Consulta</option><option value="cancelacion">Cancelación</option><option value="reclamo">Reclamo</option><option value="otro">Otro</option></select><textarea value={callNotes} onChange={e=>setCallNotes(e.target.value)} placeholder="Notas" className="field-input min-h-24"/></div><button className="action-primary mt-5 w-full"><Plus className="h-4 w-4"/>Guardar llamada</button></form></div>}
 </div>;
};
const Metric=({icon:Icon,label,value,detail}:{icon:React.ComponentType<{className?:string}>;label:string;value:string;detail:string})=><div className="cg-card p-4"><div className="flex items-center gap-2 text-[9px] font-black uppercase tracking-wider text-zinc-500"><Icon className="h-4 w-4 text-zinc-300"/>{label}</div><p className="mt-2 text-2xl font-black text-white">{value}</p><p className="mt-1 text-[9px] text-zinc-500">{detail}</p></div>;
const ChartCard=({title,children}:{title:string;children:React.ReactNode})=><section className="cg-card p-5"><h2 className="mb-4 text-sm font-black text-white">{title}</h2>{children}</section>;
