import React,{useEffect,useState}from'react';
import{CheckCircle,DollarSign,MapPinned,Plus,RadioTower,Settings,Trash2}from'lucide-react';
import{useApp}from'../../context/AppContext';
import{deleteFareDestination,loadFareDestinations,saveFareDestination}from'../../lib/operationalIntelligenceRepository';
import{FontSizeControl}from'../FontSizeControl';
import type{FareDestination}from'../../types';

export const SettingsModule:React.FC=()=>{
 const{fareConfig,updateFareConfig,currentCompany,currentRole}=useApp();
 const isOperator=currentRole==='operator';
 const canManageFares=['super_admin','company_admin','operator'].includes(currentRole);
 const canViewFares=canManageFares;
 const[baseFare,setBaseFare]=useState(fareConfig.baseFare),[pricePerKm,setPricePerKm]=useState(fareConfig.pricePerKm),[pricePerMinuteWait,setPricePerMinuteWait]=useState(fareConfig.pricePerMinuteWait),[nightSurchargePercent,setNightSurchargePercent]=useState(fareConfig.nightSurchargePercent),[savedSuccess,setSavedSuccess]=useState(false);
 const[destinations,setDestinations]=useState<FareDestination[]>([]),[destName,setDestName]=useState(''),[matchText,setMatchText]=useState(''),[destFare,setDestFare]=useState(''),[fareError,setFareError]=useState(''),[savingDestination,setSavingDestination]=useState(false);
 const reload=async()=>{if(!canViewFares||currentCompany.id==='network')return;try{setDestinations(await loadFareDestinations(currentCompany.id));setFareError('');}catch(e){setFareError(e instanceof Error?e.message:'No fue posible cargar el tarifario.');}};
 useEffect(()=>{void reload();},[currentCompany.id,canViewFares]);
 useEffect(()=>{setBaseFare(fareConfig.baseFare);setPricePerKm(fareConfig.pricePerKm);setPricePerMinuteWait(fareConfig.pricePerMinuteWait);setNightSurchargePercent(fareConfig.nightSurchargePercent);},[fareConfig]);
 const handleSave=async(e:React.FormEvent)=>{e.preventDefault();if(!canManageFares)return;await updateFareConfig({...fareConfig,baseFare,pricePerKm,pricePerMinuteWait,nightSurchargePercent});setSavedSuccess(true);setTimeout(()=>setSavedSuccess(false),3000);};
 const addDestination=async(e:React.FormEvent)=>{e.preventDefault();if(!canManageFares||savingDestination)return;const amount=Number(destFare);const name=destName.trim();const matcher=(matchText.trim()||name).toLowerCase();if(!name||!Number.isFinite(amount)||amount<0){setFareError('Ingresa un destino o sector y un valor válido.');return;}setSavingDestination(true);try{await saveFareDestination(currentCompany.id,{name,matchText:matcher,fareAmount:amount});setDestName('');setMatchText('');setDestFare('');setFareError('');await reload();}catch(err){setFareError(err instanceof Error?err.message:'No fue posible guardar la tarifa.');}finally{setSavingDestination(false);}};
 const removeDestination=async(item:FareDestination)=>{if(!window.confirm(`¿Eliminar la tarifa de ${item.name}?`))return;try{await deleteFareDestination(currentCompany.id,item.id);await reload();}catch(err){setFareError(err instanceof Error?err.message:'No fue posible eliminar la tarifa.');}};
 return <div className="mx-auto max-w-4xl space-y-5">
  <div className="rounded-2xl border border-amber-400/20 bg-gradient-to-br from-amber-400/[0.08] to-transparent p-5"><h1 className="flex items-center gap-2 text-2xl font-extrabold text-white">{isOperator?<DollarSign className="h-6 w-6 text-amber-300"/>:<Settings className="h-6 w-6 text-blue-500"/>}{isOperator?'Tarifario':canManageFares?'Configuración y Tarifario':'Configuración'}</h1><p className="mt-1 text-xs leading-relaxed text-zinc-400">{isOperator?'Hoja simple para consultar, agregar y mantener los valores de la central durante el despacho.':`Configuración operativa de ${currentCompany.name}.`}</p></div>
  {!isOperator&&<section className="rounded-2xl border border-blue-500/20 bg-[#0d0d0f] p-5 shadow-xl"><div className="flex flex-col gap-5 sm:flex-row sm:items-start sm:justify-between"><div className="max-w-xl"><h2 className="text-sm font-black text-white">Accesibilidad visual</h2><p className="mt-1 text-xs leading-relaxed text-zinc-500">Elige el tamaño de letra más cómodo. El cambio se aplica inmediatamente en esta pantalla.</p></div><FontSizeControl/></div></section>}
  {canManageFares&&<>
   <form onSubmit={handleSave} className="space-y-4 rounded-2xl border border-zinc-800 bg-[#0d0d0f] p-5 shadow-xl"><div><h2 className="flex items-center gap-2 text-base font-extrabold text-white"><DollarSign className="h-5 w-5 text-emerald-400"/>Valores generales</h2><p className="mt-1 text-[10px] text-zinc-500">Valores rápidos de referencia para la central.</p></div><div className="grid gap-3 sm:grid-cols-2"><NumberField label="Bajada de bandera ($)" value={baseFare} onChange={setBaseFare}/><NumberField label="Precio por kilómetro ($)" value={pricePerKm} onChange={setPricePerKm}/><NumberField label="Minuto de espera ($)" value={pricePerMinuteWait} onChange={setPricePerMinuteWait}/><NumberField label="Recargo nocturno (%)" value={nightSurchargePercent} onChange={setNightSurchargePercent}/></div>{!isOperator&&<div className="rounded-xl border border-zinc-800 bg-zinc-950/50 p-3 text-xs"><p className="flex items-center gap-2 font-bold text-blue-400"><RadioTower className="h-4 w-4"/>Frecuencia VHF de respaldo</p><p className="mt-1 font-mono text-zinc-300">{currentCompany.vhfFrequency||'No configurada'}</p></div>}{savedSuccess&&<div className="flex items-center gap-2 rounded-xl border border-emerald-500/30 bg-emerald-500/10 p-3 text-xs font-bold text-emerald-300"><CheckCircle className="h-4 w-4"/>Tarifa general actualizada</div>}<button className="w-full rounded-xl bg-blue-600 px-6 py-3 text-xs font-black text-white sm:w-auto">Guardar valores generales</button></form>
   <section className="rounded-2xl border border-amber-500/25 bg-[#0d0d0f] p-5 shadow-xl"><div className="flex items-start gap-3"><div className="rounded-xl border border-amber-500/25 bg-amber-500/10 p-2 text-amber-300"><MapPinned className="h-5 w-5"/></div><div><h2 className="font-black text-white">Hoja de tarifas por destino</h2><p className="mt-1 text-xs leading-relaxed text-zinc-500">Escribe el sector o destino y su valor. El campo “texto para detectar” es opcional; si lo dejas vacío usaremos automáticamente el nombre del destino.</p></div></div>
    <form onSubmit={addDestination} className="mt-5 grid gap-2 md:grid-cols-[1fr_1.1fr_.65fr_auto]"><input value={destName} onChange={e=>setDestName(e.target.value)} placeholder="Destino / sector" className={inputClass}/><input value={matchText} onChange={e=>setMatchText(e.target.value)} placeholder="Texto para detectar (opcional)" className={inputClass}/><input type="number" min="0" step="100" value={destFare} onChange={e=>setDestFare(e.target.value)} placeholder="Valor $" className={inputClass}/><button disabled={savingDestination} className="flex min-h-11 items-center justify-center gap-1.5 rounded-xl bg-amber-400 px-4 py-2.5 text-xs font-black text-zinc-950 disabled:opacity-50"><Plus className="h-4 w-4"/>{savingDestination?'Guardando…':'Agregar'}</button></form>
    {fareError&&<p className="mt-3 rounded-lg border border-rose-500/20 bg-rose-500/10 px-3 py-2 text-xs text-rose-300">{fareError}</p>}
    <div className="mt-4 overflow-hidden rounded-xl border border-zinc-800"><div className="grid grid-cols-[1fr_auto] bg-zinc-950/80 px-3 py-2 text-[9px] font-black uppercase tracking-wider text-zinc-500"><span>Destino / sector</span><span>Valor</span></div>{destinations.map(item=><div key={item.id} className="grid grid-cols-[1fr_auto] items-center gap-3 border-t border-zinc-800 bg-zinc-950/35 px-3 py-3"><div className="min-w-0"><p className="truncate text-sm font-black text-white">{item.name}</p><p className="mt-0.5 truncate text-[9px] text-zinc-600">Detecta: {item.matchText}</p></div><div className="flex items-center gap-2"><strong className="whitespace-nowrap text-base text-emerald-300">${Math.round(item.fareAmount).toLocaleString('es-CL')}</strong><button type="button" onClick={()=>void removeDestination(item)} className="grid h-9 w-9 place-items-center rounded-lg border border-rose-500/20 bg-rose-500/10 text-rose-300" title={`Eliminar ${item.name}`}><Trash2 className="h-4 w-4"/></button></div></div>)}{!destinations.length&&!fareError&&<p className="border-t border-zinc-800 p-5 text-center text-xs text-zinc-600">Aún no hay tarifas. Usa los campos de arriba para ingresar la primera.</p>}</div>
   </section>
  </>}
 </div>;
};
const inputClass='min-h-11 w-full rounded-xl border border-zinc-700 bg-zinc-950 px-3 py-2.5 text-sm text-white outline-none placeholder:text-zinc-600 focus:border-amber-400';
const NumberField=({label,value,onChange}:{label:string;value:number;onChange:(v:number)=>void})=><label><span className="block text-[10px] font-black uppercase tracking-wider text-zinc-500">{label}</span><input required min="0" type="number" value={value} onChange={e=>onChange(Number(e.target.value))} className={`${inputClass} mt-1`}/></label>;
