import React,{useEffect,useState}from'react';
import{CheckCircle,DollarSign,MapPinned,Plus,RadioTower,Settings,Trash2}from'lucide-react';
import{useApp}from'../../context/AppContext';
import{deleteFareDestination,loadFareDestinations,saveFareDestination}from'../../lib/operationalIntelligenceRepository';
import{FontSizeControl}from'../FontSizeControl';
import type{FareDestination}from'../../types';

export const SettingsModule:React.FC=()=>{
 const{fareConfig,updateFareConfig,currentCompany,currentRole}=useApp();
 const canManageFares=currentRole==='super_admin'||currentRole==='company_admin';
 const canViewFares=canManageFares||currentRole==='operator';
 const[baseFare,setBaseFare]=useState(fareConfig.baseFare),[pricePerKm,setPricePerKm]=useState(fareConfig.pricePerKm),[pricePerMinuteWait,setPricePerMinuteWait]=useState(fareConfig.pricePerMinuteWait),[nightSurchargePercent,setNightSurchargePercent]=useState(fareConfig.nightSurchargePercent),[savedSuccess,setSavedSuccess]=useState(false);
 const[destinations,setDestinations]=useState<FareDestination[]>([]),[destName,setDestName]=useState(''),[matchText,setMatchText]=useState(''),[destFare,setDestFare]=useState(''),[fareError,setFareError]=useState('');
 const reload=async()=>{if(!canViewFares||currentCompany.id==='network')return;try{setDestinations(await loadFareDestinations(currentCompany.id));setFareError('');}catch(e){setFareError(e instanceof Error?e.message:'No fue posible cargar tarifas por destino.');}};
 useEffect(()=>{void reload();},[currentCompany.id,canViewFares]);
 const handleSave=async(e:React.FormEvent)=>{e.preventDefault();if(!canManageFares)return;await updateFareConfig({...fareConfig,baseFare,pricePerKm,pricePerMinuteWait,nightSurchargePercent});setSavedSuccess(true);setTimeout(()=>setSavedSuccess(false),3000);};
 const addDestination=async(e:React.FormEvent)=>{e.preventDefault();if(!canManageFares)return;const amount=Number(destFare);if(!destName.trim()||!matchText.trim()||!Number.isFinite(amount)||amount<0){setFareError('Completa nombre, texto de coincidencia y tarifa válida.');return;}try{await saveFareDestination(currentCompany.id,{name:destName,matchText,fareAmount:amount});setDestName('');setMatchText('');setDestFare('');await reload();}catch(err){setFareError(err instanceof Error?err.message:'No fue posible guardar la tarifa.');}};
 return <div className="max-w-4xl space-y-6">
  <div><h1 className="flex items-center gap-2 text-2xl font-extrabold text-white"><Settings className="h-6 w-6 text-blue-500"/>{canManageFares?'Configuración y tarifas':currentRole==='operator'?'Tarifario':'Configuración'}</h1><p className="mt-1 text-xs text-zinc-400">{currentRole==='operator'?'Consulta los valores vigentes de la central. Solo la administración puede modificarlos.':`Personaliza la lectura de Central GO desde este dispositivo${canManageFares?' y administra los parámetros operativos de la central.':'.'}`}</p></div>
  <section className="rounded-2xl border border-blue-500/20 bg-[#0d0d0f] p-5 shadow-xl"><div className="flex flex-col gap-5 sm:flex-row sm:items-start sm:justify-between"><div className="max-w-xl"><h2 className="text-sm font-black text-white">Accesibilidad visual</h2><p className="mt-1 text-xs leading-relaxed text-zinc-500">Elige el tamaño de letra que te resulte más cómodo. El cambio se aplica inmediatamente en toda la aplicación y queda guardado en este dispositivo para las próximas sesiones.</p><div className="mt-3 rounded-xl border border-zinc-800 bg-zinc-950/50 px-3 py-2.5 text-[10px] leading-relaxed text-zinc-500"><strong className="text-zinc-300">Importante:</strong> solo cambia la lectura del texto; mapas, tarjetas y botones mantienen su estructura para no romper la operación.</div></div><FontSizeControl/></div></section>
  {canManageFares&&<>
   <form onSubmit={handleSave} className="space-y-5 rounded-2xl border border-zinc-800 bg-[#0d0d0f] p-6 shadow-xl"><h3 className="flex items-center gap-2 border-b border-zinc-800 pb-3 font-extrabold text-white"><DollarSign className="h-5 w-5 text-emerald-400"/>Tarifario digital ({currentCompany.name})</h3><div className="grid gap-4 sm:grid-cols-2"><NumberField label="Bajada de bandera ($)" value={baseFare} onChange={setBaseFare}/><NumberField label="Precio por kilómetro ($)" value={pricePerKm} onChange={setPricePerKm}/><NumberField label="Minuto de espera ($)" value={pricePerMinuteWait} onChange={setPricePerMinuteWait}/><NumberField label="Recargo nocturno (%)" value={nightSurchargePercent} onChange={setNightSurchargePercent}/></div><div className="rounded-xl border border-zinc-800 bg-zinc-950/50 p-4 text-xs"><p className="flex items-center gap-2 font-bold text-blue-400"><RadioTower className="h-4 w-4"/>Frecuencia VHF de respaldo</p><p className="mt-1 font-mono text-zinc-300">{currentCompany.vhfFrequency||'No configurada'}</p></div>{savedSuccess&&<div className="flex items-center gap-2 rounded-xl border border-emerald-500/30 bg-emerald-500/10 p-3 text-xs font-bold text-emerald-300"><CheckCircle className="h-4 w-4"/>Configuración guardada</div>}<button className="rounded-xl bg-blue-600 px-6 py-3 text-xs font-black text-white">Guardar tarifa general</button></form>
   <section className="rounded-2xl border border-amber-500/20 bg-[#0d0d0f] p-6 shadow-xl"><div className="flex items-start gap-3"><div className="rounded-xl border border-amber-500/25 bg-amber-500/10 p-2 text-amber-300"><MapPinned className="h-5 w-5"/></div><div><h2 className="font-black text-white">Tarifas fijas por destino</h2><p className="mt-1 text-xs leading-relaxed text-zinc-500">Ejemplo: <strong className="text-zinc-300">San Javier → $8.000</strong>. Cuando el destino escrito contenga el texto configurado, la carrera tomará esa tarifa automáticamente.</p></div></div><form onSubmit={addDestination} className="mt-5 grid gap-2 md:grid-cols-[1fr_1.2fr_.7fr_auto]"><input value={destName} onChange={e=>setDestName(e.target.value)} placeholder="Nombre: San Javier" className={inputClass}/><input value={matchText} onChange={e=>setMatchText(e.target.value)} placeholder="Detectar texto: san javier" className={inputClass}/><input type="number" min="0" step="500" value={destFare} onChange={e=>setDestFare(e.target.value)} placeholder="$ 8.000" className={inputClass}/><button className="flex items-center justify-center gap-1.5 rounded-xl bg-amber-400 px-4 py-2.5 text-xs font-black text-zinc-950"><Plus className="h-4 w-4"/>Agregar</button></form>{fareError&&<p className="mt-3 text-xs text-rose-300">{fareError}</p>}<div className="mt-4 space-y-2">{destinations.map(item=><div key={item.id} className="flex items-center justify-between gap-3 rounded-xl border border-zinc-800 bg-zinc-950/60 p-3"><div><p className="text-xs font-black text-white">{item.name} · <span className="text-emerald-300">${Math.round(item.fareAmount).toLocaleString('es-CL')}</span></p><p className="mt-0.5 text-[9px] text-zinc-600">Se activa cuando el destino contiene “{item.matchText}”</p></div><button onClick={()=>void deleteFareDestination(currentCompany.id,item.id).then(reload)} className="rounded-lg border border-rose-500/20 bg-rose-500/10 p-2 text-rose-300"><Trash2 className="h-4 w-4"/></button></div>)}{!destinations.length&&<p className="rounded-xl border border-zinc-800 p-4 text-center text-xs text-zinc-600">Aún no hay tarifas fijas por destino.</p>}</div></section>
  </>}
  {currentRole==='operator'&&<>
   <section className="rounded-2xl border border-emerald-500/20 bg-[#0d0d0f] p-6 shadow-xl"><div className="flex items-center justify-between gap-3 border-b border-zinc-800 pb-3"><h2 className="flex items-center gap-2 font-extrabold text-white"><DollarSign className="h-5 w-5 text-emerald-400"/>Tarifa general ({currentCompany.name})</h2><span className="rounded-full border border-blue-500/20 bg-blue-500/10 px-2.5 py-1 text-[9px] font-black text-blue-300">SOLO LECTURA</span></div><div className="mt-4 grid gap-3 sm:grid-cols-2"><FareValue label="Bajada de bandera" value={fareConfig.baseFare}/><FareValue label="Precio por kilómetro" value={fareConfig.pricePerKm}/><FareValue label="Minuto de espera" value={fareConfig.pricePerMinuteWait}/><FareValue label="Recargo nocturno" value={fareConfig.nightSurchargePercent} suffix="%" money={false}/></div></section>
   <section className="rounded-2xl border border-amber-500/20 bg-[#0d0d0f] p-6 shadow-xl"><div className="flex items-start gap-3"><div className="rounded-xl border border-amber-500/25 bg-amber-500/10 p-2 text-amber-300"><MapPinned className="h-5 w-5"/></div><div><h2 className="font-black text-white">Tarifas fijas por destino</h2><p className="mt-1 text-xs text-zinc-500">Valores vigentes para informar al pasajero durante el despacho.</p></div></div>{fareError&&<p className="mt-3 text-xs text-rose-300">{fareError}</p>}<div className="mt-4 space-y-2">{destinations.filter(item=>item.active).map(item=><div key={item.id} className="flex items-center justify-between gap-3 rounded-xl border border-zinc-800 bg-zinc-950/60 p-3"><div><p className="text-xs font-black text-white">{item.name}</p><p className="mt-0.5 text-[9px] text-zinc-600">Destino que contiene “{item.matchText}”</p></div><strong className="text-sm text-emerald-300">${Math.round(item.fareAmount).toLocaleString('es-CL')}</strong></div>)}{!destinations.filter(item=>item.active).length&&!fareError&&<p className="rounded-xl border border-zinc-800 p-4 text-center text-xs text-zinc-600">No hay tarifas fijas por destino configuradas.</p>}</div></section>
  </>}
 </div>;
};
const inputClass='w-full rounded-xl border border-zinc-800 bg-zinc-950 px-3 py-2.5 text-xs text-white outline-none focus:border-amber-400';
const NumberField=({label,value,onChange}:{label:string;value:number;onChange:(v:number)=>void})=><label><span className="block text-[10px] font-black uppercase tracking-wider text-zinc-500">{label}</span><input required type="number" value={value} onChange={e=>onChange(Number(e.target.value))} className={`${inputClass} mt-1`}/></label>;
const FareValue=({label,value,suffix='',money=true}:{label:string;value:number;suffix?:string;money?:boolean})=><div className="rounded-xl border border-zinc-800 bg-zinc-950/60 p-4"><p className="text-[9px] font-black uppercase tracking-wider text-zinc-500">{label}</p><p className="mt-1 text-lg font-black text-white">{money?'$':''}{Math.round(value).toLocaleString('es-CL')}{suffix}</p></div>;
