import React,{useState}from'react';
import{Route,Search,Zap,X}from'lucide-react';
import{useApp}from'../../context/AppContext';
import{TRIP_STATUS_LABELS}from'../../lib/labels';
import type{Trip}from'../../types';
import{cancelTripWithSource}from'../../lib/operationsHistoryRepository';

export const TripsModule:React.FC=()=>{
 const{trips,setNewTripModalOpen,setSelectedTripForDetail,autoAssignClosestDriver}=useApp();
 const[searchTerm,setSearchTerm]=useState(''),[statusFilter,setStatusFilter]=useState('all');
 const[cancelTarget,setCancelTarget]=useState<Trip|null>(null),[cancelSource,setCancelSource]=useState<'client'|'operator'>('client'),[cancelReason,setCancelReason]=useState('Cliente canceló la carrera'),[cancelling,setCancelling]=useState(false),[error,setError]=useState('');
 const filteredTrips=trips.filter(t=>{const q=searchTerm.toLowerCase();const match=[t.code,t.clientName,t.clientPhone,t.origin.address,t.destination.address,t.driverUnitNumber??'',t.driverName??'',t.vehiclePlate??''].join(' ').toLowerCase().includes(q);return match&&(statusFilter==='all'||t.status===statusFilter);});
 const submitCancel=async(e:React.FormEvent)=>{e.preventDefault();if(!cancelTarget)return;setCancelling(true);setError('');try{await cancelTripWithSource(cancelTarget.id,cancelReason,cancelSource);setCancelTarget(null);}catch(err){setError(err instanceof Error?err.message:'No fue posible cancelar la carrera.');}finally{setCancelling(false);}};
 return <div className="space-y-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><h1 className="flex items-center gap-2 text-2xl font-extrabold text-white"><Route className="h-6 w-6 text-blue-500"/>Gestión de despachos y viajes</h1><p className="mt-1 text-xs text-zinc-400">Búsqueda operacional por cliente, teléfono, calle, móvil, chofer o patente.</p></div><button onClick={()=>setNewTripModalOpen(true)} className="flex items-center gap-2 rounded-xl bg-amber-400 px-4 py-2.5 text-xs font-black text-zinc-950"><Zap className="h-4 w-4"/>Nueva carrera</button></div>
 <div className="flex flex-col gap-3 rounded-xl border border-zinc-800 bg-[#0d0d0f] p-4 md:flex-row md:items-center md:justify-between"><label className="relative w-full md:w-[430px]"><Search className="absolute left-3 top-3 h-4 w-4 text-zinc-500"/><input value={searchTerm} onChange={e=>setSearchTerm(e.target.value)} placeholder="Código, cliente, teléfono, dirección, móvil o patente…" className="w-full rounded-lg border border-zinc-800 bg-[#121215] py-2 pl-9 pr-4 text-xs text-zinc-200 outline-none focus:border-blue-500"/></label><div className="flex flex-wrap gap-1.5">{[['all','Todos'],['pending','Pendientes'],['assigned','Asignados'],['en_route','En camino'],['in_progress','En viaje'],['completed','Completados'],['cancelled','Cancelados']].map(([id,label])=><button key={id} onClick={()=>setStatusFilter(id)} className={`rounded-lg px-3 py-1.5 text-[10px] font-black ${statusFilter===id?'bg-blue-600 text-white':'bg-zinc-950 text-zinc-500'}`}>{label}</button>)}</div></div>
 {error&&<div className="rounded-xl border border-rose-500/30 bg-rose-500/10 p-3 text-xs text-rose-200">{error}</div>}
 <div className="overflow-hidden rounded-xl border border-zinc-800 bg-[#0d0d0f]"><div className="overflow-x-auto"><table className="w-full min-w-[1100px] text-left text-xs"><thead className="bg-[#121215] text-[9px] font-black uppercase text-zinc-500"><tr><th className="p-3">Fecha/Código</th><th className="p-3">Cliente</th><th className="p-3">Origen / destino</th><th className="p-3">Móvil / vehículo</th><th className="p-3">Pago</th><th className="p-3">Tarifa</th><th className="p-3">Estado</th><th className="p-3 text-right">Acciones</th></tr></thead><tbody className="divide-y divide-zinc-800/80">{filteredTrips.map(trip=><tr key={trip.id} onClick={()=>setSelectedTripForDetail(trip)} className="cursor-pointer hover:bg-zinc-900/60"><td className="p-3"><p className="font-mono font-bold text-blue-300">{trip.code}</p><p className="mt-0.5 text-[9px] text-zinc-600">{new Date(trip.createdAt).toLocaleString('es-CL')}</p></td><td className="p-3"><p className="font-bold text-white">{trip.clientName}</p><p className="text-[10px] text-zinc-500">{trip.clientPhone}</p></td><td className="p-3 max-w-sm"><p className="truncate text-zinc-200">📍 {trip.origin.address}</p><p className="mt-0.5 truncate text-[10px] text-zinc-500">🏁 {trip.destination.address}</p></td><td className="p-3"><p className="font-black text-amber-300">{trip.driverUnitNumber??'Sin asignar'}</p><p className="text-[9px] text-zinc-600">{trip.vehiclePlate??trip.driverName??''}</p></td><td className="p-3 text-zinc-300">{trip.paymentMethod.replace('_',' ')}</td><td className="p-3 font-black text-emerald-300">${Math.round(trip.finalFare??trip.estimatedFare).toLocaleString('es-CL')}</td><td className="p-3"><span className={`rounded-md border px-2 py-1 text-[9px] font-black ${trip.status==='cancelled'?'border-rose-500/30 bg-rose-500/10 text-rose-300':trip.status==='completed'?'border-emerald-500/30 bg-emerald-500/10 text-emerald-300':'border-blue-500/20 bg-blue-500/10 text-blue-300'}`}>{TRIP_STATUS_LABELS[trip.status]}</span>{trip.cancelReason&&<p className="mt-1 max-w-40 truncate text-[8px] text-zinc-600">{trip.cancelReason}</p>}</td><td className="p-3"><div className="flex justify-end gap-1.5">{trip.status==='pending'&&<button onClick={e=>{e.stopPropagation();void autoAssignClosestDriver(trip.id);}} className="rounded-lg bg-blue-600 px-2.5 py-1.5 text-[9px] font-black text-white">Auto-asignar</button>}{!['completed','cancelled'].includes(trip.status)&&<button onClick={e=>{e.stopPropagation();setCancelTarget(trip);setCancelSource('client');setCancelReason('Cliente canceló la carrera');}} className="rounded-lg border border-rose-500/30 bg-rose-500/10 px-2.5 py-1.5 text-[9px] font-black text-rose-300">Cancelar</button>}</div></td></tr>)}</tbody></table>{!filteredTrips.length&&<div className="p-12 text-center text-xs text-zinc-600">No se encontraron carreras.</div>}</div></div>
 {cancelTarget&&<div className="fixed inset-0 z-[120] flex items-center justify-center bg-black/85 p-4 backdrop-blur-md"><form onSubmit={submitCancel} className="w-full max-w-md rounded-3xl border border-zinc-700 bg-[#0d0d0f] p-6"><div className="flex items-start justify-between"><div><p className="text-[9px] font-black uppercase tracking-widest text-rose-300">Cancelar {cancelTarget.code}</p><h2 className="mt-1 text-lg font-black text-white">Motivo de cancelación</h2></div><button type="button" onClick={()=>setCancelTarget(null)} className="p-2 text-zinc-500"><X className="h-4 w-4"/></button></div><div className="mt-5 grid grid-cols-2 gap-2"><button type="button" onClick={()=>{setCancelSource('client');setCancelReason('Cliente canceló la carrera');}} className={`rounded-xl border p-3 text-xs font-black ${cancelSource==='client'?'border-amber-400 bg-amber-400 text-zinc-950':'border-zinc-800 bg-zinc-950 text-zinc-400'}`}>Canceló el cliente</button><button type="button" onClick={()=>{setCancelSource('operator');setCancelReason('Cancelación administrativa');}} className={`rounded-xl border p-3 text-xs font-black ${cancelSource==='operator'?'border-blue-500 bg-blue-600 text-white':'border-zinc-800 bg-zinc-950 text-zinc-400'}`}>Central / otro</button></div><textarea required value={cancelReason} onChange={e=>setCancelReason(e.target.value)} className="mt-3 min-h-24 w-full rounded-xl border border-zinc-800 bg-zinc-950 p-3 text-sm text-white outline-none focus:border-rose-500"/><p className="mt-2 text-[10px] leading-relaxed text-zinc-500">Si cancela el cliente y ya había un móvil asignado, ese conductor vuelve libre y recupera prioridad en la cola de despacho.</p><button disabled={cancelling} className="mt-5 w-full rounded-xl bg-rose-600 py-3 text-xs font-black text-white disabled:opacity-50">{cancelling?'Cancelando…':'Confirmar cancelación'}</button></form></div>}
 </div>;
};
