import React,{useCallback,useEffect,useState}from'react';
import{BadgeCheck,CarFront,ChevronDown,CircleDollarSign,Clock3,Gauge,Loader2,LocateFixed,MapPin,Navigation,Phone,PhoneCall,Route,Share2,ShieldCheck,Star,UserRound,X}from'lucide-react';
import logo from'../../assets/images/central-go-logo.svg';
import{cancelPassengerRide,findNearbyCentrals,getPassengerRideStatus,ratePassengerRide,requestPassengerRide,type NearbyCentral,type PassengerTripSnapshot}from'../../lib/passengerRepository';
import{PassengerLiveMap}from'./PassengerLiveMap';

const STORAGE_KEY='centralgo:passenger-profile:v1';
const clean=(value:string)=>value.trim();
const statusCopy:Record<string,{title:string;copy:string}>={pending:{title:'Buscando un móvil',copy:'Tu solicitud ya llegó a la central.'},assigned:{title:'Móvil asignado',copy:'Ya encontramos tu taxi.'},en_route:{title:'Tu taxi va en camino',copy:'Puedes seguirlo en tiempo real.'},arrived:{title:'Tu taxi llegó',copy:'El conductor ya está en tu punto de retiro.'},in_progress:{title:'Viaje iniciado',copy:'Tu carrera está en curso.'},completed:{title:'Viaje finalizado',copy:'Gracias por viajar con Central GO.'},cancelled:{title:'Carrera cancelada',copy:'La solicitud fue cancelada.'}};

export const PassengerRequestApp:React.FC=()=>{
 const[name,setName]=useState(''),[phone,setPhone]=useState(''),[pickup,setPickup]=useState(''),[destination,setDestination]=useState(''),[notes,setNotes]=useState('');
 const[position,setPosition]=useState<{lat:number;lng:number}|null>(null),[centrals,setCentrals]=useState<NearbyCentral[]>([]),[selectedCentralId,setSelectedCentralId]=useState('');
 const[locating,setLocating]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[trip,setTrip]=useState<PassengerTripSnapshot|null>(null),[routeInfo,setRouteInfo]=useState<{etaMinutes:number;distanceKm:number}|null>(null),[ratingBusy,setRatingBusy]=useState(false);

 useEffect(()=>{try{const raw=localStorage.getItem(STORAGE_KEY);if(!raw)return;const saved=JSON.parse(raw);setName(String(saved.name||''));setPhone(String(saved.phone||''));}catch{}},[]);
 useEffect(()=>{void locate();},[]);
 useEffect(()=>{if(!trip||['completed','cancelled'].includes(trip.status))return;const id=window.setInterval(()=>{void getPassengerRideStatus(trip.tripId,phone).then(setTrip).catch(()=>undefined);},3000);return()=>window.clearInterval(id);},[trip?.tripId,trip?.status,phone]);

 const detect=async(lat:number,lng:number)=>{const nearby=await findNearbyCentrals(lat,lng);setCentrals(nearby);setSelectedCentralId(current=>nearby.some(c=>c.id===current)?current:(nearby[0]?.id||''));if(!nearby.length)setError('No encontramos una central Central GO dentro de 10 km de tu ubicación.');};
 const locate=()=>{setError('');if(!navigator.geolocation){setError('Este teléfono no permite obtener ubicación GPS.');return;}setLocating(true);navigator.geolocation.getCurrentPosition((p)=>{const next={lat:p.coords.latitude,lng:p.coords.longitude};setPosition(next);setPickup(current=>current||'Mi ubicación actual');void detect(next.lat,next.lng).catch(err=>setError(err instanceof Error?err.message:'No pudimos detectar centrales cercanas.')).finally(()=>setLocating(false));},()=>{setError('Activa el GPS para detectar automáticamente las centrales disponibles cerca de ti.');setLocating(false);},{enableHighAccuracy:true,timeout:10000,maximumAge:15000});};
 const submit=async(e:React.FormEvent)=>{e.preventDefault();setError('');const n=clean(name),p=clean(phone),o=clean(pickup);if(!position){setError('Necesitamos tu ubicación para elegir una central cercana.');return;}if(!selectedCentralId){setError('No hay una central disponible dentro de 10 km.');return;}if(n.length<2){setError('Ingresa tu nombre.');return;}if(p.length<7){setError('Ingresa un teléfono válido.');return;}if(o.length<3){setError('Indica dónde debemos recogerte.');return;}setBusy(true);try{localStorage.setItem(STORAGE_KEY,JSON.stringify({name:n,phone:p}));const created=await requestPassengerRide({companyId:selectedCentralId,passengerName:n,phone:p,pickupAddress:o,pickupLat:position.lat,pickupLng:position.lng,destinationAddress:clean(destination)||'A convenir / Taxímetro',notes:clean(notes)||undefined});setTrip(created);}catch(err){setError(err instanceof Error?err.message:'No fue posible pedir el móvil.');}finally{setBusy(false);}};
 const handleRouteInfo=useCallback((next:{etaMinutes:number;distanceKm:number})=>setRouteInfo(next),[]);
 const cancel=async()=>{if(!trip||!confirm('¿Cancelar esta carrera?'))return;setBusy(true);try{setTrip(await cancelPassengerRide(trip.tripId,phone));setRouteInfo(null);}catch(err){setError(err instanceof Error?err.message:'No pudimos cancelar la carrera.');}finally{setBusy(false);}};
 const share=async()=>{if(!trip)return;const shareData={title:'Mi viaje en Central GO',text:`Viaje ${trip.code} · ${trip.centralName} · ${trip.driverName?`Conductor: ${trip.driverName}`:'Buscando conductor'}`};try{if(navigator.share)await navigator.share(shareData);else await navigator.clipboard.writeText(`${shareData.text} · ${location.href}`);}catch{}};
 const rate=async(value:number)=>{if(!trip||ratingBusy)return;setRatingBusy(true);try{setTrip(await ratePassengerRide(trip.tripId,phone,value));}catch(err){setError(err instanceof Error?err.message:'No pudimos guardar la calificación.');}finally{setRatingBusy(false);}};

 if(trip){
  const state=statusCopy[trip.status]||statusCopy.pending,tracking=['assigned','en_route','arrived'].includes(trip.status)&&trip.driverLat!=null&&trip.driverLng!=null&&trip.originLat!=null&&trip.originLng!=null;
  const riding=trip.status==='in_progress'&&trip.driverLat!=null&&trip.driverLng!=null&&trip.destinationLat!=null&&trip.destinationLng!=null&&!/^a convenir/i.test(trip.destinationAddress);
  const targetLat=riding?trip.destinationLat:trip.originLat,targetLng=riding?trip.destinationLng:trip.originLng;
  const vehicle=[trip.vehicleColor,trip.vehicleBrand,trip.vehicleModel].filter(Boolean).join(' ')||'Taxi de la central';
  return <main className="min-h-screen bg-[#07111f] text-white"><div className="mx-auto min-h-screen max-w-md pb-24">
   <header className="flex items-center justify-between px-4 py-3"><div className="flex items-center gap-2.5"><img src={logo} className="h-9 w-9"/><div><div className="text-sm font-black">Central GO</div><div className="text-[9px] font-black uppercase tracking-[.18em] text-cyan-300">Pasajero</div></div></div><button onClick={share} className="grid h-10 w-10 place-items-center rounded-xl border border-white/10 bg-white/[.05]" aria-label="Compartir viaje"><Share2 className="h-4 w-4"/></button></header>

   <section className="px-3"><div className="rounded-[26px] border border-white/10 bg-white/[.06] p-4 shadow-2xl shadow-black/25"><div className="flex items-start justify-between gap-3"><div><div className="mb-1 flex items-center gap-2"><span className={`h-2.5 w-2.5 rounded-full ${trip.status==='cancelled'?'bg-rose-400':trip.status==='completed'?'bg-emerald-400':trip.status==='arrived'?'bg-emerald-300':'bg-cyan-300 animate-pulse'}`}/><span className="text-[10px] font-black uppercase tracking-[.16em] text-slate-400">{trip.code}</span></div><h1 className="text-xl font-black tracking-tight">{state.title}</h1><p className="mt-1 text-xs font-semibold text-slate-400">{state.copy}</p></div>{routeInfo&&['assigned','en_route','in_progress'].includes(trip.status)&&<div className="shrink-0 rounded-2xl bg-cyan-400 px-3 py-2 text-center text-slate-950"><div className="text-[9px] font-black uppercase">{riding?'Destino':'Llega en'}</div><div className="text-xl font-black leading-none">{routeInfo.etaMinutes}<span className="ml-1 text-[10px]">min</span></div></div>}</div></div></section>

   {(tracking||riding)&&targetLat!=null&&targetLng!=null&&<section className="px-3 pt-3"><PassengerLiveMap driverLat={trip.driverLat!} driverLng={trip.driverLng!} originLat={targetLat} originLng={targetLng} driverHeading={trip.driverHeading} onRouteInfo={handleRouteInfo}/>{routeInfo&&trip.status!=='arrived'&&<div className="-mt-3 relative z-[500] mx-auto flex w-[86%] items-center justify-center gap-4 rounded-2xl border border-white/10 bg-[#0b1726]/95 px-4 py-2.5 shadow-xl"><span className="flex items-center gap-1.5 text-xs font-black text-cyan-200"><Route className="h-3.5 w-3.5"/>{routeInfo.distanceKm.toLocaleString('es-CL',{maximumFractionDigits:1})} km</span><span className="h-4 w-px bg-white/10"/><span className="flex items-center gap-1.5 text-xs font-black text-white"><Clock3 className="h-3.5 w-3.5"/>ETA {routeInfo.etaMinutes} min</span></div>}</section>}

   {trip.driverName&&<section className="px-3 pt-3"><div className="rounded-[24px] border border-white/10 bg-white/[.06] p-4"><div className="flex items-center gap-3">{trip.driverPhotoUrl?<img src={trip.driverPhotoUrl} className="h-14 w-14 rounded-2xl object-cover" alt="Foto del conductor"/>:<div className="grid h-14 w-14 place-items-center rounded-2xl bg-cyan-400/10"><UserRound className="h-6 w-6 text-cyan-300"/></div>}<div className="min-w-0 flex-1"><div className="flex items-center gap-1.5"><h2 className="truncate text-base font-black">{trip.driverName}</h2><BadgeCheck className="h-4 w-4 shrink-0 text-cyan-300"/></div><div className="mt-1 flex flex-wrap items-center gap-2 text-xs font-bold text-slate-400"><span className="flex items-center gap-1 text-amber-300"><Star className="h-3.5 w-3.5 fill-current"/>{trip.driverRating?.toFixed(1)??'5.0'}</span>{trip.driverTripsCompleted!=null&&<span>{trip.driverTripsCompleted.toLocaleString('es-CL')} viajes</span>}</div></div><div className="rounded-xl bg-cyan-400 px-3 py-2 text-center text-slate-950"><div className="text-[9px] font-black uppercase">Móvil</div><div className="text-lg font-black leading-none">{trip.driverUnitNumber??trip.vehicleUnitNumber??'—'}</div></div></div><div className="mt-3 grid grid-cols-2 gap-2"><Mini icon={CarFront} label="Vehículo" value={vehicle}/><Mini icon={ShieldCheck} label="Central" value={trip.centralName}/>{trip.vehiclePlate&&<Mini icon={Gauge} label="Patente" value={trip.vehiclePlate}/>}<Mini icon={MapPin} label="Retiro" value={trip.originAddress}/></div></div></section>}

   {!trip.driverName&&trip.status==='pending'&&<section className="px-3 pt-3"><div className="rounded-[24px] border border-cyan-300/15 bg-cyan-300/[.05] p-5 text-center"><Loader2 className="mx-auto h-7 w-7 animate-spin text-cyan-300"/><div className="mt-3 text-sm font-black">Buscando la mejor unidad disponible</div><p className="mt-1 text-xs text-slate-400">La central verá tu solicitud inmediatamente.</p></div></section>}

   {trip.status==='completed'&&<section className="px-3 pt-3"><div className="rounded-[24px] border border-emerald-400/20 bg-emerald-400/[.07] p-4 text-center"><div className="text-sm font-black">¿Cómo estuvo tu viaje?</div><div className="mt-3 flex justify-center gap-2">{[1,2,3,4,5].map(value=><button key={value} disabled={ratingBusy} onClick={()=>void rate(value)} className="p-1"><Star className={`h-7 w-7 ${trip.rating&&value<=trip.rating?'fill-amber-300 text-amber-300':'text-slate-600'}`}/></button>)}</div><p className="mt-2 text-[11px] text-slate-400">Tu calificación ayuda a mejorar la calidad de la central.</p></div></section>}

   <section className="px-3 pt-3"><details className="group rounded-[22px] border border-white/10 bg-white/[.04]"><summary className="flex cursor-pointer list-none items-center justify-between px-4 py-3 text-xs font-black text-slate-300"><span>Detalles de la carrera</span><ChevronDown className="h-4 w-4 transition group-open:rotate-180"/></summary><div className="space-y-2 border-t border-white/10 p-3"><Info icon={ShieldCheck} label="Central" value={trip.centralName}/><Info icon={MapPin} label="Retiro" value={trip.originAddress}/><Info icon={Route} label="Destino" value={trip.destinationAddress}/>{trip.estimatedFare&&trip.estimatedFare>0?<Info icon={CircleDollarSign} label="Tarifa estimada" value={`$${Math.round(trip.estimatedFare).toLocaleString('es-CL')}`}/>:null}</div></details></section>

   {error&&<div className="mx-3 mt-3 rounded-2xl border border-rose-400/25 bg-rose-400/10 px-4 py-3 text-xs font-bold text-rose-100">{error}</div>}

   <div className="fixed inset-x-0 bottom-0 z-[900] border-t border-white/10 bg-[#07111f]/95 p-3 backdrop-blur-xl"><div className="mx-auto flex max-w-md gap-2">{trip.centralPhone&&<a href={`tel:${trip.centralPhone}`} className="flex h-12 flex-1 items-center justify-center gap-2 rounded-2xl border border-white/10 bg-white/[.06] text-xs font-black"><PhoneCall className="h-4 w-4"/>Central</a>}{['pending','assigned','en_route','arrived'].includes(trip.status)&&<button disabled={busy} onClick={()=>void cancel()} className="flex h-12 flex-1 items-center justify-center gap-2 rounded-2xl border border-rose-400/20 bg-rose-400/10 text-xs font-black text-rose-200"><X className="h-4 w-4"/>Cancelar</button>}{['completed','cancelled'].includes(trip.status)&&<button onClick={()=>{setTrip(null);setRouteInfo(null);setError('');}} className="flex h-12 flex-1 items-center justify-center rounded-2xl bg-cyan-400 text-xs font-black text-slate-950">Pedir otro móvil</button>}</div></div>
  </div></main>;
 }

 const selected=centrals.find(c=>c.id===selectedCentralId);
 return <main className="min-h-screen bg-[#07111f] px-3 py-3 text-white sm:py-5"><div className="mx-auto max-w-md"><header className="mb-3 flex items-center gap-3 px-1"><img src={logo} className="h-11 w-11 drop-shadow-xl"/><div><p className="text-[10px] font-black uppercase tracking-[.18em] text-cyan-300">Central GO</p><h1 className="text-2xl font-black tracking-tight">Pide tu taxi</h1></div></header><form onSubmit={submit} className="rounded-[26px] border border-white/10 bg-white/[.06] p-4 shadow-2xl shadow-black/30 backdrop-blur-xl"><div className="space-y-3">
  <div className="rounded-2xl border border-cyan-300/20 bg-cyan-300/[.07] px-3 py-2.5"><div className="flex items-center justify-between gap-3"><div className="min-w-0">{locating?<div className="flex items-center gap-2 text-sm font-black"><Loader2 className="h-4 w-4 animate-spin"/>Buscando central cercana…</div>:selected?<><div className="text-[9px] font-black uppercase tracking-[.15em] text-cyan-300">Central automática</div><div className="truncate text-sm font-black">{selected.name} <span className="text-xs text-slate-400">· {selected.distanceKm.toLocaleString('es-CL')} km</span></div></>:<div className="text-sm font-black text-slate-300">Sin central disponible</div>}</div><button type="button" onClick={locate} className="grid h-9 w-9 shrink-0 place-items-center rounded-xl bg-cyan-400 text-slate-950" aria-label="Actualizar ubicación"><LocateFixed className="h-4 w-4"/></button></div>{centrals.length>1&&<select value={selectedCentralId} onChange={e=>setSelectedCentralId(e.target.value)} className={`${inputClass} mt-2 h-10`}>{centrals.map(c=><option key={c.id} value={c.id}>{c.name} · {c.distanceKm.toLocaleString('es-CL')} km</option>)}</select>}</div>

  <div className="grid gap-2"><Field icon={MapPin} label="Retiro"><input value={pickup} onChange={e=>setPickup(e.target.value)} placeholder="Tu ubicación o dirección" className={inputClass}/></Field><Field icon={Route} label="Destino"><input value={destination} onChange={e=>setDestination(e.target.value)} placeholder="Opcional · puedes decidirlo después" className={inputClass}/></Field></div>
  <div className="grid grid-cols-2 gap-2"><Field icon={UserRound} label="Nombre"><input value={name} onChange={e=>setName(e.target.value)} autoComplete="name" placeholder="Tu nombre" className={inputClass}/></Field><Field icon={Phone} label="Teléfono"><input value={phone} onChange={e=>setPhone(e.target.value)} inputMode="tel" autoComplete="tel" placeholder="+56 9…" className={inputClass}/></Field></div>
  <details className="group rounded-2xl border border-white/10 bg-black/10"><summary className="flex cursor-pointer list-none items-center justify-between px-3 py-2.5 text-[11px] font-black text-slate-400"><span>Agregar referencia para el conductor</span><ChevronDown className="h-4 w-4 transition group-open:rotate-180"/></summary><div className="border-t border-white/10 p-2"><input value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Ej: portón azul, entrada lateral…" className={inputClass}/></div></details>
  {position&&<div className="flex items-center gap-1.5 text-[10px] font-bold text-emerald-300"><Navigation className="h-3.5 w-3.5"/>GPS verificado · central dentro de 10 km</div>}
  {error&&<div className="rounded-2xl border border-rose-400/25 bg-rose-400/10 px-3 py-2.5 text-xs font-bold text-rose-100">{error}</div>}
  <button disabled={busy||locating||!selectedCentralId} className="flex h-13 w-full items-center justify-center gap-2 rounded-2xl bg-cyan-400 px-5 text-sm font-black text-slate-950 shadow-xl shadow-cyan-950/30 transition active:scale-[.98] disabled:opacity-60">{busy?<Loader2 className="h-5 w-5 animate-spin"/>:<CarFront className="h-5 w-5"/>}{busy?'Enviando…':'PEDIR MÓVIL'}</button>
  <p className="text-center text-[10px] leading-4 text-slate-500">La central se elige automáticamente por cercanía. Puedes cambiarla solo si hay otra dentro de 10 km.</p>
 </div></form></div></main>;
};

const inputClass='h-11 w-full rounded-xl border border-white/10 bg-black/20 px-3 text-xs font-bold text-white outline-none placeholder:text-slate-600 focus:border-cyan-300/50 focus:ring-2 focus:ring-cyan-300/10 disabled:opacity-60';
const Field:React.FC<React.PropsWithChildren<{icon:React.ElementType;label:string}>>=({icon:Icon,label,children})=><label className="block"><span className="mb-1.5 flex items-center gap-1.5 text-[10px] font-black uppercase tracking-wide text-slate-400"><Icon className="h-3.5 w-3.5 text-cyan-300"/>{label}</span>{children}</label>;
const Info:React.FC<{icon:React.ElementType;label:string;value:string}>=({icon:Icon,label,value})=><div className="flex gap-3 rounded-xl border border-white/10 bg-black/15 p-2.5"><div className="grid h-8 w-8 shrink-0 place-items-center rounded-lg bg-cyan-400/10"><Icon className="h-3.5 w-3.5 text-cyan-300"/></div><div className="min-w-0"><div className="text-[9px] font-black uppercase tracking-wider text-slate-500">{label}</div><div className="mt-0.5 break-words text-xs font-black text-slate-100">{value}</div></div></div>;
const Mini:React.FC<{icon:React.ElementType;label:string;value:string}>=({icon:Icon,label,value})=><div className="min-w-0 rounded-xl bg-black/15 p-2.5"><div className="flex items-center gap-1.5 text-[9px] font-black uppercase text-slate-500"><Icon className="h-3 w-3 text-cyan-300"/>{label}</div><div className="mt-1 truncate text-[11px] font-black text-slate-200">{value}</div></div>;
