import React,{lazy,Suspense,useEffect,useState} from 'react';
import {useApp} from './context/AppContext';import {AuthProvider,useAuth} from './context/AuthContext';import {CommercialAppProvider} from './context/CommercialAppProvider';
import {Header} from './components/Header';import {Sidebar} from './components/Sidebar';import {DriverMobileView} from './components/pwa/DriverMobileView';import {DriverToCentralRadioPanel} from './components/pwa/DriverToCentralRadioPanel';import {CentralRadioReceiver} from './components/radio/CentralRadioReceiver';
import {NewTripModal} from './components/modals/NewTripModal';import {SOSAlertModal} from './components/modals/SOSAlertModal';import {TripDetailModal} from './components/modals/TripDetailModal';import {VHFDispatchModal} from './components/modals/VHFDispatchModal';import {NotificationsDrawer} from './components/notifications/NotificationsDrawer';import {LoginScreen} from './components/auth/LoginScreen';import {OnboardingScreen} from './components/auth/OnboardingScreen';import {PartnerApplicationStatusScreen} from './components/auth/PartnerApplicationStatusScreen';import {DriverOnboardingPortal} from './components/driver/DriverOnboardingPortal';import {registerServiceWorker} from './lib/pwa';import {ErrorBoundary} from './components/system/ErrorBoundary';import {CommercialGate} from './components/system/CommercialGate';import {TrialGate} from './components/system/TrialGate';import {ArrowLeft,Loader2,ShieldAlert,ShieldCheck} from 'lucide-react';

const DashboardModule=lazy(()=>import('./components/modules/DashboardModule').then(module=>({default:module.DashboardModule})));
const OperatorWorkspace=lazy(()=>import('./components/modules/OperatorWorkspace').then(module=>({default:module.OperatorWorkspace})));
const LiveMap=lazy(()=>import('./components/map/LiveMap').then(module=>({default:module.LiveMap})));
const TripsModule=lazy(()=>import('./components/modules/TripsModule').then(module=>({default:module.TripsModule})));
const DriversModule=lazy(()=>import('./components/modules/DriversModule').then(module=>({default:module.DriversModule})));
const VehiclesModule=lazy(()=>import('./components/modules/VehiclesModule').then(module=>({default:module.VehiclesModule})));
const ClientsModule=lazy(()=>import('./components/modules/ClientsModule').then(module=>({default:module.ClientsModule})));
const OperatorsModule=lazy(()=>import('./components/modules/OperatorsModule').then(module=>({default:module.OperatorsModule})));
const CompaniesModule=lazy(()=>import('./components/modules/CompaniesModule').then(module=>({default:module.CompaniesModule})));
const UsersModule=lazy(()=>import('./components/modules/UsersModule').then(module=>({default:module.UsersModule})));
const ReportsModule=lazy(()=>import('./components/modules/ReportsModule').then(module=>({default:module.ReportsModule})));
const HistoryModule=lazy(()=>import('./components/modules/HistoryModule').then(module=>({default:module.HistoryModule})));
const SettingsModule=lazy(()=>import('./components/modules/SettingsModule').then(module=>({default:module.SettingsModule})));
const ProfileModule=lazy(()=>import('./components/modules/ProfileModule').then(module=>({default:module.ProfileModule})));
const HelpModule=lazy(()=>import('./components/modules/HelpModule').then(module=>({default:module.HelpModule})));
const CommercialGlobalAdminDashboard=lazy(()=>import('./components/modules/CommercialGlobalAdminDashboard').then(module=>({default:module.CommercialGlobalAdminDashboard})));
const PartnerDashboard=lazy(()=>import('./components/modules/PartnerDashboard').then(module=>({default:module.PartnerDashboard})));
const CentralsNetworkModule=lazy(()=>import('./components/modules/CentralsNetworkModule').then(module=>({default:module.CentralsNetworkModule})));
const PartnersNetworkModule=lazy(()=>import('./components/modules/PartnersNetworkModule').then(module=>({default:module.PartnersNetworkModule})));
const CommissionsNetworkModule=lazy(()=>import('./components/modules/CommissionsNetworkModule').then(module=>({default:module.CommissionsNetworkModule})));
const PlansNetworkModule=lazy(()=>import('./components/modules/PlansNetworkModule').then(module=>({default:module.PlansNetworkModule})));
const NetworkSupportModule=lazy(()=>import('./components/modules/NetworkSupportModule').then(module=>({default:module.NetworkSupportModule})));

const ModuleLoader=()=> <div className="flex min-h-72 items-center justify-center" role="status" aria-live="polite"><Loader2 className="h-6 w-6 animate-spin text-amber-400"/><span className="sr-only">Cargando módulo</span></div>;
const MODULE_ACCESS:Record<string,string[]>={dashboard:['super_admin','regional_partner','sales_partner','company_admin','operator'],network_centrals:['super_admin','regional_partner','sales_partner'],partners_network:['super_admin','regional_partner'],commissions_network:['super_admin','regional_partner','sales_partner'],plans_network:['super_admin','regional_partner','sales_partner'],network_support:['super_admin','regional_partner','sales_partner'],live_map:['super_admin'],trips:['company_admin','operator'],drivers:['company_admin','operator'],vehicles:['company_admin'],clients:['company_admin','operator'],operators:['company_admin'],companies:['super_admin'],users:['super_admin'],reports:['company_admin'],history:['super_admin','company_admin'],settings:['super_admin','company_admin'],profile:['super_admin','regional_partner','sales_partner','company_admin','operator'],help:['super_admin','regional_partner','sales_partner','company_admin','operator']};

const MainAppContent:React.FC=()=>{const{currentRole,activeModule,setActiveModule,setNewTripModalOpen}=useApp();const[sidebarOpen,setSidebarOpen]=useState(false),[notificationsOpen,setNotificationsOpen]=useState(false);useEffect(()=>{const h=(e:KeyboardEvent)=>{const canDispatch=['operator','company_admin','super_admin'].includes(currentRole);if(!canDispatch)return;const target=e.target as HTMLElement|null;const typing=['INPUT','TEXTAREA','SELECT'].includes(target?.tagName||'');const key=e.key.toLowerCase();const code=e.code;if(key==='f2'||code==='F2'){e.preventDefault();e.stopPropagation();setNewTripModalOpen(true);return;}if((key==='f3'||code==='F3')&&!typing){e.preventDefault();e.stopPropagation();window.dispatchEvent(new CustomEvent('centralgo:toggle-queue-view'));return;}if((e.ctrlKey||e.metaKey)&&key==='k'){e.preventDefault();e.stopPropagation();if(activeModule!=='dashboard')setActiveModule('dashboard');window.setTimeout(()=>window.dispatchEvent(new CustomEvent('centralgo:focus-search')),80);return;}if(key==='escape')window.dispatchEvent(new CustomEvent('centralgo:escape'));};window.addEventListener('keydown',h,true);return()=>window.removeEventListener('keydown',h,true);},[currentRole,activeModule,setActiveModule,setNewTripModalOpen]);
 const authorized=(module:string)=>MODULE_ACCESS[module]?.includes(currentRole)??false;useEffect(()=>{if(!authorized(activeModule))setActiveModule('dashboard');},[activeModule,currentRole,setActiveModule]);
 const render=()=>{if(!authorized(activeModule))return currentRole==='super_admin'?<CommercialGlobalAdminDashboard/>:<DashboardModule/>;switch(activeModule){case'dashboard':if(currentRole==='operator'||currentRole==='company_admin')return <OperatorWorkspace/>;if(currentRole==='super_admin')return <CommercialGlobalAdminDashboard/>;if(currentRole==='regional_partner'||currentRole==='sales_partner')return <PartnerDashboard/>;return <DashboardModule/>;case'network_centrals':return <CentralsNetworkModule/>;case'partners_network':return <PartnersNetworkModule/>;case'commissions_network':return <CommissionsNetworkModule/>;case'plans_network':return <PlansNetworkModule/>;case'network_support':return <NetworkSupportModule/>;case'live_map':return <div className="space-y-4"><h1 className="text-2xl font-extrabold text-white">Mapa en Tiempo Real</h1><LiveMap height="h-[calc(100vh-200px)]"/></div>;case'trips':return <TripsModule/>;case'drivers':return <DriversModule/>;case'vehicles':return <VehiclesModule/>;case'clients':return <ClientsModule/>;case'operators':return <OperatorsModule/>;case'companies':return <CompaniesModule/>;case'users':return <UsersModule/>;case'reports':return <ReportsModule/>;case'history':return <HistoryModule/>;case'settings':return <SettingsModule/>;case'profile':return <ProfileModule/>;case'help':return <HelpModule/>;default:return <DashboardModule/>;}};
 return <div className="cg-operational min-h-screen bg-[#09090b] text-zinc-100 flex flex-col"><Header onToggleMenu={()=>setSidebarOpen(open=>!open)} onToggleNotifications={()=>setNotificationsOpen(!notificationsOpen)}/><div className="flex-1 flex relative"><Sidebar isOpen={sidebarOpen} onClose={()=>setSidebarOpen(false)}/><main className={`flex-1 overflow-y-auto mx-auto w-full min-h-[calc(100vh-65px)] ${['operator','company_admin'].includes(currentRole)?'p-2 md:p-2.5 max-w-[1900px]':['super_admin','regional_partner','sales_partner'].includes(currentRole)?'p-4 md:p-6 max-w-[1600px]':'p-4 md:p-6 max-w-7xl'}`}><Suspense fallback={<ModuleLoader/>}>{render()}</Suspense></main></div><NewTripModal/><SOSAlertModal/><TripDetailModal/><VHFDispatchModal/><CentralRadioReceiver/><NotificationsDrawer isOpen={notificationsOpen} onClose={()=>setNotificationsOpen(false)}/></div>};

const PasswordSetupGate:React.FC=()=>{const{updatePassword}=useAuth();const[password,setPassword]=useState(''),[confirm,setConfirm]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');const submit=async(e:React.FormEvent)=>{e.preventDefault();setError('');if(password.length<10){setError('Usa al menos 10 caracteres.');return;}if(password!==confirm){setError('Las contraseñas no coinciden.');return;}setBusy(true);try{await updatePassword(password);window.location.replace('/');}catch(err){setError(err instanceof Error?err.message:'No fue posible guardar la contraseña.');setBusy(false);}};return <main className="min-h-screen bg-[#070709] p-4 text-zinc-100 flex items-center justify-center"><section className="w-full max-w-md rounded-3xl border border-zinc-800 bg-[#0d0d0f] p-6 sm:p-8 shadow-2xl"><div className="flex items-center gap-3"><div className="flex h-12 w-12 items-center justify-center rounded-2xl border border-amber-400/60 bg-zinc-950 text-amber-300"><ShieldCheck className="h-6 w-6"/></div><div><p className="text-[9px] font-black uppercase tracking-widest text-amber-300">Central GO · Cuenta oficial</p><h1 className="text-xl font-black text-white">Crea tu contraseña</h1></div></div><p className="mt-5 text-sm leading-relaxed text-zinc-400">Tu correo ya fue verificado. Define una contraseña personal para entrar a tu central.</p><form onSubmit={submit} className="mt-5 space-y-4"><input required minLength={10} type="password" autoComplete="new-password" value={password} onChange={e=>setPassword(e.target.value)} className="w-full rounded-xl border border-zinc-800 bg-zinc-950 px-4 py-3 text-sm outline-none focus:border-amber-400/70" placeholder="Contraseña · mínimo 10 caracteres"/><input required minLength={10} type="password" autoComplete="new-password" value={confirm} onChange={e=>setConfirm(e.target.value)} className="w-full rounded-xl border border-zinc-800 bg-zinc-950 px-4 py-3 text-sm outline-none focus:border-amber-400/70" placeholder="Repetir contraseña"/>{error&&<div className="rounded-xl border border-rose-500/25 bg-rose-500/10 px-4 py-3 text-sm text-rose-200">{error}</div>}<button disabled={busy} className="flex w-full items-center justify-center gap-2 rounded-xl bg-amber-400 px-4 py-3.5 text-sm font-black text-zinc-950 disabled:opacity-60">{busy?<Loader2 className="h-4 w-4 animate-spin"/>:<ShieldCheck className="h-4 w-4"/>}{busy?'Guardando…':'Guardar contraseña y continuar'}</button></form></section></main>};
const WrongDriverRoute=()=> <main className="min-h-screen bg-zinc-950 p-5 text-zinc-100 flex items-center justify-center"><section className="max-w-md rounded-3xl border border-amber-500/25 bg-[#0d0d0f] p-7 text-center"><ShieldAlert className="mx-auto h-9 w-9 text-amber-300"/><h1 className="mt-4 text-xl font-black">Acceso exclusivo para conductores</h1><button onClick={()=>location.href='/'} className="mt-5 inline-flex gap-2 rounded-xl bg-amber-400 px-4 py-3 text-xs font-black text-zinc-950"><ArrowLeft className="h-4 w-4"/>Volver al panel</button></section></main>;
const IdentityErrorScreen:React.FC<{message:string}>=({message})=><main className="min-h-screen bg-zinc-950 p-5 text-zinc-100 flex items-center justify-center"><section className="w-full max-w-md rounded-3xl border border-rose-500/25 bg-[#0d0d0f] p-7 text-center"><ShieldAlert className="mx-auto h-9 w-9 text-rose-300"/><h1 className="mt-4 text-xl font-black">No pudimos validar tu cuenta</h1><p className="mt-3 text-sm leading-relaxed text-zinc-400">{message}</p><button onClick={()=>location.reload()} className="mt-5 rounded-xl bg-amber-400 px-5 py-3 text-xs font-black text-zinc-950">Reintentar</button><p className="mt-3 text-[10px] text-zinc-600">No crees otra cuenta mientras aparece este mensaje.</p></section></main>;
const AuthenticatedShell:React.FC=()=>{const{session,authUser,loading,effectiveRole,profile,memberships,saasAccount,partnerApplication,identityError}=useAuth();const driverPath=location.pathname.startsWith('/driver');const needsPasswordSetup=Boolean(authUser?.user_metadata?.needs_password_setup);useEffect(()=>{registerServiceWorker();},[]);if(loading)return <main className="min-h-screen bg-zinc-950 text-zinc-200 flex items-center justify-center"><Loader2 className="h-5 w-5 animate-spin text-amber-400"/></main>;if(!session)return <LoginScreen/>;if(needsPasswordSetup)return <PasswordSetupGate/>;const configured=Boolean(profile?.globalRole)||Boolean(saasAccount)||memberships.length>0;if(identityError&&!configured)return <IdentityErrorScreen message={identityError}/>;if(!configured)return <OnboardingScreen/>;if(saasAccount?.accountKind==='sales_partner'&&!profile?.globalRole)return <PartnerApplicationStatusScreen/>;if(partnerApplication?.status==='pending'&&!profile?.globalRole)return <PartnerApplicationStatusScreen/>;if(saasAccount?.accountKind==='driver'&&effectiveRole!=='driver')return <DriverOnboardingPortal/>;if(effectiveRole==='driver'&&!driverPath){location.replace('/driver');return null;}if(driverPath&&effectiveRole!=='driver')return <WrongDriverRoute/>;if(driverPath)return <CommercialAppProvider><div className="cg-operational"><DriverMobileView/><DriverToCentralRadioPanel/></div></CommercialAppProvider>;return <CommercialAppProvider><TrialGate><MainAppContent/></TrialGate></CommercialAppProvider>};
export default function App(){return <ErrorBoundary><AuthProvider><CommercialGate><AuthenticatedShell/></CommercialGate></AuthProvider></ErrorBoundary>}
