-- Central GO commercial core schema (prepared, not yet applied)
-- Designed for Supabase/PostgreSQL with multi-tenant Row Level Security.

create extension if not exists pgcrypto;

create type public.centralgo_global_role as enum ('super_admin', 'regional_partner', 'sales_partner');
create type public.centralgo_company_role as enum ('company_admin', 'operator', 'driver');
create type public.centralgo_driver_status as enum ('available', 'en_route', 'in_trip', 'paused', 'offline', 'sos');
create type public.centralgo_trip_status as enum ('pending', 'assigned', 'en_route', 'arrived', 'in_progress', 'completed', 'cancelled');
create type public.centralgo_payment_method as enum ('efectivo', 'transferencia', 'posnet_tarjeta', 'cuenta_corriente');
create type public.centralgo_vehicle_status as enum ('active', 'maintenance', 'inactive');

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  name text not null,
  phone text,
  avatar_url text,
  global_role public.centralgo_global_role,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.companies (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  code text not null unique,
  phone text,
  address text,
  vhf_frequency text,
  logo_url text,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.company_memberships (
  id uuid primary key default gen_random_uuid(),
  company_id uuid not null references public.companies(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  role public.centralgo_company_role not null,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  unique (company_id, user_id, role)
);

create index company_memberships_user_idx on public.company_memberships(user_id, company_id) where active;

create table public.vehicles (
  id uuid primary key default gen_random_uuid(),
  company_id uuid not null references public.companies(id) on delete cascade,
  unit_number text not null,
  license_plate text not null,
  brand text not null,
  model text not null,
  year integer not null check (year between 1950 and 2200),
  color text,
  capacity integer not null default 4 check (capacity between 1 and 20),
  pet_friendly boolean not null default false,
  wheelchair_accessible boolean not null default false,
  air_conditioning boolean not null default false,
  technical_inspection_expiry date,
  status public.centralgo_vehicle_status not null default 'active',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (company_id, unit_number),
  unique (company_id, license_plate)
);

create table public.drivers (
  id uuid primary key default gen_random_uuid(),
  company_id uuid not null references public.companies(id) on delete cascade,
  user_id uuid references public.profiles(id) on delete set null,
  vehicle_id uuid references public.vehicles(id) on delete set null,
  unit_number text not null,
  display_name text not null,
  phone text,
  license_number text not null,
  license_expiry date,
  photo_url text,
  status public.centralgo_driver_status not null default 'offline',
  rating numeric(3,2) not null default 5.00 check (rating between 0 and 5),
  total_trips_completed integer not null default 0 check (total_trips_completed >= 0),
  today_earnings numeric(14,2) not null default 0,
  commission_balance numeric(14,2) not null default 0,
  sos_active boolean not null default false,
  sos_timestamp timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (company_id, unit_number),
  unique (company_id, license_number)
);

create index drivers_company_status_idx on public.drivers(company_id, status);
create index drivers_user_idx on public.drivers(user_id) where user_id is not null;

create table public.driver_locations (
  driver_id uuid primary key references public.drivers(id) on delete cascade,
  company_id uuid not null references public.companies(id) on delete cascade,
  lat double precision not null check (lat between -90 and 90),
  lng double precision not null check (lng between -180 and 180),
  address text,
  speed_kmh numeric(7,2) check (speed_kmh is null or speed_kmh >= 0),
  heading_degrees numeric(6,2) check (heading_degrees is null or (heading_degrees >= 0 and heading_degrees < 360)),
  accuracy_meters numeric(8,2),
  recorded_at timestamptz not null default now()
);

create index driver_locations_company_idx on public.driver_locations(company_id, recorded_at desc);

create table public.driver_location_history (
  id bigint generated by default as identity primary key,
  driver_id uuid not null references public.drivers(id) on delete cascade,
  company_id uuid not null references public.companies(id) on delete cascade,
  lat double precision not null check (lat between -90 and 90),
  lng double precision not null check (lng between -180 and 180),
  speed_kmh numeric(7,2),
  heading_degrees numeric(6,2),
  accuracy_meters numeric(8,2),
  recorded_at timestamptz not null default now()
);

create index driver_location_history_driver_time_idx on public.driver_location_history(driver_id, recorded_at desc);
create index driver_location_history_company_time_idx on public.driver_location_history(company_id, recorded_at desc);

create table public.clients (
  id uuid primary key default gen_random_uuid(),
  company_id uuid not null references public.companies(id) on delete cascade,
  name text not null,
  phone text not null,
  email text,
  rating numeric(3,2) not null default 5.00 check (rating between 0 and 5),
  is_vip boolean not null default false,
  notes text,
  has_current_account boolean not null default false,
  total_trips integer not null default 0 check (total_trips >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index clients_company_phone_idx on public.clients(company_id, phone);

create table public.client_addresses (
  id uuid primary key default gen_random_uuid(),
  client_id uuid not null references public.clients(id) on delete cascade,
  company_id uuid not null references public.companies(id) on delete cascade,
  label text not null,
  address text not null,
  lat double precision not null check (lat between -90 and 90),
  lng double precision not null check (lng between -180 and 180),
  created_at timestamptz not null default now()
);

create table public.trips (
  id uuid primary key default gen_random_uuid(),
  company_id uuid not null references public.companies(id) on delete cascade,
  code text not null,
  client_id uuid references public.clients(id) on delete set null,
  client_name text not null,
  client_phone text not null,
  origin_address text not null,
  origin_lat double precision not null check (origin_lat between -90 and 90),
  origin_lng double precision not null check (origin_lng between -180 and 180),
  origin_notes text,
  destination_address text not null,
  destination_lat double precision not null check (destination_lat between -90 and 90),
  destination_lng double precision not null check (destination_lng between -180 and 180),
  destination_notes text,
  status public.centralgo_trip_status not null default 'pending',
  driver_id uuid references public.drivers(id) on delete set null,
  driver_unit_number text,
  driver_name text,
  operator_user_id uuid references public.profiles(id) on delete set null,
  operator_name text not null,
  vehicle_type_requested text check (vehicle_type_requested is null or vehicle_type_requested in ('standard','pet','wheelchair','vip')),
  estimated_distance_km numeric(10,2) not null default 0 check (estimated_distance_km >= 0),
  estimated_duration_mins integer not null default 0 check (estimated_duration_mins >= 0),
  estimated_fare numeric(14,2) not null default 0 check (estimated_fare >= 0),
  final_fare numeric(14,2) check (final_fare is null or final_fare >= 0),
  is_fixed_fare boolean not null default false,
  fixed_fare_amount numeric(14,2) check (fixed_fare_amount is null or fixed_fare_amount >= 0),
  payment_method public.centralgo_payment_method not null default 'efectivo',
  notes text,
  created_at timestamptz not null default now(),
  assigned_at timestamptz,
  en_route_at timestamptz,
  arrived_at timestamptz,
  started_at timestamptz,
  completed_at timestamptz,
  cancelled_at timestamptz,
  cancel_reason text,
  rating numeric(3,2) check (rating is null or rating between 0 and 5),
  feedback text,
  version integer not null default 1 check (version > 0),
  unique (company_id, code)
);

create index trips_company_status_created_idx on public.trips(company_id, status, created_at desc);
create index trips_driver_active_idx on public.trips(driver_id, status) where status not in ('completed','cancelled');
create index trips_client_idx on public.trips(client_id, created_at desc) where client_id is not null;

create table public.fare_configs (
  company_id uuid primary key references public.companies(id) on delete cascade,
  base_fare numeric(14,2) not null default 0,
  price_per_km numeric(14,2) not null default 0,
  price_per_minute_wait numeric(14,2) not null default 0,
  night_surcharge_percent numeric(6,2) not null default 0,
  sunday_surcharge_percent numeric(6,2) not null default 0,
  cancellation_fee numeric(14,2) not null default 0,
  currency_symbol text not null default '$',
  updated_at timestamptz not null default now()
);

create table public.sos_events (
  id uuid primary key default gen_random_uuid(),
  company_id uuid not null references public.companies(id) on delete cascade,
  driver_id uuid not null references public.drivers(id) on delete cascade,
  trip_id uuid references public.trips(id) on delete set null,
  lat double precision,
  lng double precision,
  address text,
  activated_at timestamptz not null default now(),
  resolved_at timestamptz,
  resolved_by uuid references public.profiles(id) on delete set null,
  resolution_notes text
);

create index sos_events_company_open_idx on public.sos_events(company_id, activated_at desc) where resolved_at is null;

create table public.notifications (
  id uuid primary key default gen_random_uuid(),
  company_id uuid not null references public.companies(id) on delete cascade,
  recipient_user_id uuid references public.profiles(id) on delete cascade,
  title text not null,
  message text not null,
  type text not null check (type in ('info','warning','sos','success','trip')),
  read boolean not null default false,
  related_id uuid,
  created_at timestamptz not null default now()
);

create index notifications_recipient_idx on public.notifications(recipient_user_id, read, created_at desc);

create table public.audit_logs (
  id bigint generated by default as identity primary key,
  company_id uuid references public.companies(id) on delete set null,
  user_id uuid references public.profiles(id) on delete set null,
  user_name text,
  user_role text,
  action text not null,
  description text not null,
  ip_address inet,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index audit_logs_company_time_idx on public.audit_logs(company_id, created_at desc);
create index audit_logs_user_time_idx on public.audit_logs(user_id, created_at desc);

create table public.driver_settlements (
  id uuid primary key default gen_random_uuid(),
  company_id uuid not null references public.companies(id) on delete cascade,
  driver_id uuid not null references public.drivers(id) on delete cascade,
  amount numeric(14,2) not null,
  notes text,
  settled_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now()
);

-- Updated-at helper.
create or replace function public.centralgo_touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger profiles_touch before update on public.profiles for each row execute function public.centralgo_touch_updated_at();
create trigger companies_touch before update on public.companies for each row execute function public.centralgo_touch_updated_at();
create trigger vehicles_touch before update on public.vehicles for each row execute function public.centralgo_touch_updated_at();
create trigger drivers_touch before update on public.drivers for each row execute function public.centralgo_touch_updated_at();
create trigger clients_touch before update on public.clients for each row execute function public.centralgo_touch_updated_at();
create trigger fare_configs_touch before update on public.fare_configs for each row execute function public.centralgo_touch_updated_at();

-- Auth profile bootstrap. Never grants a privileged role automatically.
create or replace function public.centralgo_handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, name, phone)
  values (
    new.id,
    coalesce(nullif(new.raw_user_meta_data ->> 'name', ''), split_part(coalesce(new.email, 'usuario'), '@', 1)),
    nullif(new.raw_user_meta_data ->> 'phone', '')
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

create trigger centralgo_auth_user_created
after insert on auth.users
for each row execute procedure public.centralgo_handle_new_user();

-- Authorization helpers use SECURITY DEFINER to avoid recursive RLS evaluation.
create or replace function public.centralgo_is_super_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.profiles p
    where p.id = auth.uid() and p.active and p.global_role = 'super_admin'
  );
$$;

create or replace function public.centralgo_is_company_member(target_company uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select public.centralgo_is_super_admin() or exists (
    select 1
    from public.company_memberships m
    where m.company_id = target_company
      and m.user_id = auth.uid()
      and m.active
  );
$$;

create or replace function public.centralgo_has_company_role(target_company uuid, allowed_roles public.centralgo_company_role[])
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select public.centralgo_is_super_admin() or exists (
    select 1
    from public.company_memberships m
    where m.company_id = target_company
      and m.user_id = auth.uid()
      and m.active
      and m.role = any(allowed_roles)
  );
$$;

-- Enable RLS everywhere containing operational/customer data.
alter table public.profiles enable row level security;
alter table public.companies enable row level security;
alter table public.company_memberships enable row level security;
alter table public.vehicles enable row level security;
alter table public.drivers enable row level security;
alter table public.driver_locations enable row level security;
alter table public.driver_location_history enable row level security;
alter table public.clients enable row level security;
alter table public.client_addresses enable row level security;
alter table public.trips enable row level security;
alter table public.fare_configs enable row level security;
alter table public.sos_events enable row level security;
alter table public.notifications enable row level security;
alter table public.audit_logs enable row level security;
alter table public.driver_settlements enable row level security;

-- Profiles.
create policy profiles_read_self_or_super on public.profiles for select to authenticated
using (id = auth.uid() or public.centralgo_is_super_admin());
create policy profiles_update_self on public.profiles for update to authenticated
using (id = auth.uid()) with check (id = auth.uid());

-- Companies and memberships.
create policy companies_read_member on public.companies for select to authenticated
using (public.centralgo_is_company_member(id));
create policy companies_admin_write on public.companies for update to authenticated
using (public.centralgo_has_company_role(id, array['company_admin']::public.centralgo_company_role[]))
with check (public.centralgo_has_company_role(id, array['company_admin']::public.centralgo_company_role[]));

create policy memberships_read on public.company_memberships for select to authenticated
using (user_id = auth.uid() or public.centralgo_has_company_role(company_id, array['company_admin']::public.centralgo_company_role[]));
create policy memberships_admin_insert on public.company_memberships for insert to authenticated
with check (public.centralgo_has_company_role(company_id, array['company_admin']::public.centralgo_company_role[]));
create policy memberships_admin_update on public.company_memberships for update to authenticated
using (public.centralgo_has_company_role(company_id, array['company_admin']::public.centralgo_company_role[]))
with check (public.centralgo_has_company_role(company_id, array['company_admin']::public.centralgo_company_role[]));
create policy memberships_admin_delete on public.company_memberships for delete to authenticated
using (public.centralgo_has_company_role(company_id, array['company_admin']::public.centralgo_company_role[]));

-- Fleet.
create policy vehicles_read_member on public.vehicles for select to authenticated
using (public.centralgo_is_company_member(company_id));
create policy vehicles_admin_insert on public.vehicles for insert to authenticated
with check (public.centralgo_has_company_role(company_id, array['company_admin']::public.centralgo_company_role[]));
create policy vehicles_admin_update on public.vehicles for update to authenticated
using (public.centralgo_has_company_role(company_id, array['company_admin']::public.centralgo_company_role[]))
with check (public.centralgo_has_company_role(company_id, array['company_admin']::public.centralgo_company_role[]));
create policy vehicles_admin_delete on public.vehicles for delete to authenticated
using (public.centralgo_has_company_role(company_id, array['company_admin']::public.centralgo_company_role[]));

create policy drivers_read_member on public.drivers for select to authenticated
using (public.centralgo_is_company_member(company_id));
create policy drivers_admin_insert on public.drivers for insert to authenticated
with check (public.centralgo_has_company_role(company_id, array['company_admin']::public.centralgo_company_role[]));
create policy drivers_admin_update on public.drivers for update to authenticated
using (public.centralgo_has_company_role(company_id, array['company_admin']::public.centralgo_company_role[]))
with check (public.centralgo_has_company_role(company_id, array['company_admin']::public.centralgo_company_role[]));

-- Location: drivers may write only their own location; operators/admins may read fleet positions.
create policy driver_locations_read_member on public.driver_locations for select to authenticated
using (public.centralgo_is_company_member(company_id));
create policy driver_locations_write_owner on public.driver_locations for insert to authenticated
with check (
  exists (select 1 from public.drivers d where d.id = driver_id and d.user_id = auth.uid() and d.company_id = company_id)
  or public.centralgo_has_company_role(company_id, array['company_admin','operator']::public.centralgo_company_role[])
);
create policy driver_locations_update_owner on public.driver_locations for update to authenticated
using (
  exists (select 1 from public.drivers d where d.id = driver_id and d.user_id = auth.uid() and d.company_id = company_id)
  or public.centralgo_has_company_role(company_id, array['company_admin','operator']::public.centralgo_company_role[])
)
with check (
  exists (select 1 from public.drivers d where d.id = driver_id and d.user_id = auth.uid() and d.company_id = company_id)
  or public.centralgo_has_company_role(company_id, array['company_admin','operator']::public.centralgo_company_role[])
);

create policy driver_history_read_ops on public.driver_location_history for select to authenticated
using (public.centralgo_has_company_role(company_id, array['company_admin','operator']::public.centralgo_company_role[]));
create policy driver_history_write_owner on public.driver_location_history for insert to authenticated
with check (
  exists (select 1 from public.drivers d where d.id = driver_id and d.user_id = auth.uid() and d.company_id = company_id)
  or public.centralgo_has_company_role(company_id, array['company_admin','operator']::public.centralgo_company_role[])
);

-- Customers.
create policy clients_read_ops on public.clients for select to authenticated
using (public.centralgo_has_company_role(company_id, array['company_admin','operator']::public.centralgo_company_role[]));
create policy clients_write_ops on public.clients for all to authenticated
using (public.centralgo_has_company_role(company_id, array['company_admin','operator']::public.centralgo_company_role[]))
with check (public.centralgo_has_company_role(company_id, array['company_admin','operator']::public.centralgo_company_role[]));

create policy client_addresses_read_ops on public.client_addresses for select to authenticated
using (public.centralgo_has_company_role(company_id, array['company_admin','operator']::public.centralgo_company_role[]));
create policy client_addresses_write_ops on public.client_addresses for all to authenticated
using (public.centralgo_has_company_role(company_id, array['company_admin','operator']::public.centralgo_company_role[]))
with check (public.centralgo_has_company_role(company_id, array['company_admin','operator']::public.centralgo_company_role[]));

-- Trips: operators/admins manage; the assigned driver can read the trip.
create policy trips_read_company on public.trips for select to authenticated
using (
  public.centralgo_has_company_role(company_id, array['company_admin','operator']::public.centralgo_company_role[])
  or exists (select 1 from public.drivers d where d.id = driver_id and d.user_id = auth.uid())
);
create policy trips_insert_ops on public.trips for insert to authenticated
with check (public.centralgo_has_company_role(company_id, array['company_admin','operator']::public.centralgo_company_role[]));
create policy trips_update_ops on public.trips for update to authenticated
using (public.centralgo_has_company_role(company_id, array['company_admin','operator']::public.centralgo_company_role[]))
with check (public.centralgo_has_company_role(company_id, array['company_admin','operator']::public.centralgo_company_role[]));

-- Pricing and settlements.
create policy fare_configs_read_member on public.fare_configs for select to authenticated
using (public.centralgo_is_company_member(company_id));
create policy fare_configs_admin_write on public.fare_configs for all to authenticated
using (public.centralgo_has_company_role(company_id, array['company_admin']::public.centralgo_company_role[]))
with check (public.centralgo_has_company_role(company_id, array['company_admin']::public.centralgo_company_role[]));

create policy settlements_read_admin on public.driver_settlements for select to authenticated
using (public.centralgo_has_company_role(company_id, array['company_admin']::public.centralgo_company_role[]));
create policy settlements_write_admin on public.driver_settlements for insert to authenticated
with check (public.centralgo_has_company_role(company_id, array['company_admin']::public.centralgo_company_role[]));

-- SOS: company operators/admins plus the originating driver.
create policy sos_read_authorized on public.sos_events for select to authenticated
using (
  public.centralgo_has_company_role(company_id, array['company_admin','operator']::public.centralgo_company_role[])
  or exists (select 1 from public.drivers d where d.id = driver_id and d.user_id = auth.uid())
);
create policy sos_insert_driver on public.sos_events for insert to authenticated
with check (
  exists (select 1 from public.drivers d where d.id = driver_id and d.user_id = auth.uid() and d.company_id = company_id)
  or public.centralgo_has_company_role(company_id, array['company_admin','operator']::public.centralgo_company_role[])
);
create policy sos_update_ops on public.sos_events for update to authenticated
using (public.centralgo_has_company_role(company_id, array['company_admin','operator']::public.centralgo_company_role[]))
with check (public.centralgo_has_company_role(company_id, array['company_admin','operator']::public.centralgo_company_role[]));

-- Notifications.
create policy notifications_read on public.notifications for select to authenticated
using (
  recipient_user_id = auth.uid()
  or (recipient_user_id is null and public.centralgo_is_company_member(company_id))
  or public.centralgo_is_super_admin()
);
create policy notifications_update_own on public.notifications for update to authenticated
using (recipient_user_id = auth.uid())
with check (recipient_user_id = auth.uid());
create policy notifications_insert_ops on public.notifications for insert to authenticated
with check (public.centralgo_has_company_role(company_id, array['company_admin','operator']::public.centralgo_company_role[]));

-- Audit logs are append-only for normal clients. Company admins can read their tenant.
create policy audit_logs_read_admin on public.audit_logs for select to authenticated
using (company_id is not null and public.centralgo_has_company_role(company_id, array['company_admin']::public.centralgo_company_role[]));
create policy audit_logs_insert_member on public.audit_logs for insert to authenticated
with check (company_id is not null and public.centralgo_is_company_member(company_id) and (user_id is null or user_id = auth.uid()));

-- Realtime publication candidates. Supabase may already have this publication;
-- adding tables is safe when executed once as a migration.
alter publication supabase_realtime add table public.trips;
alter publication supabase_realtime add table public.drivers;
alter publication supabase_realtime add table public.driver_locations;
alter publication supabase_realtime add table public.sos_events;
alter publication supabase_realtime add table public.notifications;
