create index if not exists client_addresses_client_idx on public.client_addresses(client_id);
create index if not exists client_addresses_company_idx on public.client_addresses(company_id);
create index if not exists commission_ledger_company_idx on public.commission_ledger(company_id);
create index if not exists commission_ledger_partner_idx on public.commission_ledger(partner_id);
create index if not exists commission_ledger_payment_idx on public.commission_ledger(payment_id) where payment_id is not null;
create index if not exists driver_settlements_company_idx on public.driver_settlements(company_id);
create index if not exists driver_settlements_driver_idx on public.driver_settlements(driver_id);
create index if not exists driver_settlements_settled_by_idx on public.driver_settlements(settled_by) where settled_by is not null;
create index if not exists drivers_vehicle_idx on public.drivers(vehicle_id) where vehicle_id is not null;
create index if not exists notifications_company_idx on public.notifications(company_id, created_at desc);
create index if not exists partner_payouts_partner_idx on public.partner_payouts(partner_id, requested_at desc);
create index if not exists partners_parent_idx on public.partners(parent_partner_id) where parent_partner_id is not null;
create index if not exists payments_company_idx on public.payments(company_id, created_at desc);
create index if not exists payments_subscription_idx on public.payments(subscription_id) where subscription_id is not null;
create index if not exists referrals_partner_idx on public.referrals(partner_id);
create index if not exists sos_events_driver_idx on public.sos_events(driver_id, activated_at desc);
create index if not exists sos_events_resolved_by_idx on public.sos_events(resolved_by) where resolved_by is not null;
create index if not exists sos_events_trip_idx on public.sos_events(trip_id) where trip_id is not null;
create index if not exists subscriptions_plan_idx on public.subscriptions(plan_id);
create index if not exists support_tickets_assigned_partner_idx on public.support_tickets(assigned_partner_id, created_at desc) where assigned_partner_id is not null;
create index if not exists support_tickets_company_idx on public.support_tickets(company_id, created_at desc) where company_id is not null;
create index if not exists support_tickets_created_by_idx on public.support_tickets(created_by, created_at desc);
create index if not exists trips_operator_user_idx on public.trips(operator_user_id, created_at desc) where operator_user_id is not null;
