import React,{useEffect,useState}from'react';
import{Building2,CarFront,Loader2,MailCheck,RefreshCw,ShieldCheck}from'lucide-react';
import{ONBOARDING_INTENT_KEY}from'../../context/AuthContext';
import{buildDriverInviteUrl,rememberDriverInviteToken,resolveDriverInvite,type DriverInviteTarget}from'../../lib/driverInvite';
import{googleOAuthOptions}from'../../lib/googleOAuth';
import{requireSupabase}from'../../lib/supabase';
import{AuthShell}from'./AuthShell';

const friendly=(error:unknown,fallback:string)=>{const message=error instanceof Error?error.message:String(error??'');if(/email not confirmed|email_not_confirmed/i.test(message))return'Tu correo aún no está confirmado. Revisa tu bandeja o solicita un nuevo enlace.';if(/invalid login credentials/i.test(message))return'Correo o contraseña incorrectos.';if(/user already registered|already been registered/i.test(message))return'Este correo ya está registrado. Usa “Ya tengo cuenta”.';if(/email rate limit exceeded|over_email_send_rate_limit|rate limit|too many requests/i.test(message))return'Se alcanzó temporalmente el límite de correos. Espera unos minutos antes de volver a intentarlo.';return message||fallback;};

export const DriverInviteAuthScreen:React.FC<{inviteCode:string}>=({inviteCode})=>{
 const[mode,setMode]=useState<'register'|'login'>('register');const[email,setEmail]=useState(''),[password,setPassword]=useState(''),[confirm,setConfirm]=useState('');const[busy,setBusy]=useState(false),[checking,setChecking]=useState(true);const[error,setError]=useState(''),[notice,setNotice]=useState('');const[target,setTarget]=useState<DriverInviteTarget|null>(null);const[confirmationEmail,setConfirmationEmail]=useState('');const[resendCooldown,setResendCooldown]=useState(0);
 useEffect(()=>{rememberDriverInviteToken(inviteCode);window.localStorage.setItem(ONBOARDING_INTENT_KEY,'driver');let active=true;void resolveDriverInvite(inviteCode).then(result=>{if(!active)return;if(!result)throw new Error('Este enlace de invitación ya no está activo.');setTarget(result);}).catch(err=>{if(active)setError(friendly(err,'No fue posible validar la invitación.'));}).finally(()=>{if(active)setChecking(false);});return()=>{active=false;};},[inviteCode]);
 useEffect(()=>{if(resendCooldown<=0)return;const timer=window.setInterval(()=>setResendCooldown(value=>Math.max(0,value-1)),1000);return()=>window.clearInterval(timer);},[resendCooldown]);
 const redirectUrl=()=>buildDriverInviteUrl(inviteCode);
 const google=async()=>{if(!target)return;setBusy(true);setError('');setNotice('');try{rememberDriverInviteToken(inviteCode);window.localStorage.setItem(ONBOARDING_INTENT_KEY,'driver');const{error:oauthError}=await requireSupabase().auth.signInWithOAuth({provider:'google',options:googleOAuthOptions(redirectUrl())});if(oauthError)throw oauthError;}catch(err){setError(friendly(err,'No fue posible continuar con Google.'));setBusy(false);}};
 const resendConfirmation=async()=>{const normalized=(confirmationEmail||email).trim().toLowerCase();if(!normalized.includes('@')||resendCooldown>0||busy)return;setBusy(true);setError('');try{const{error:resendError}=await requireSupabase().auth.resend({type:'signup',email:normalized,options:{emailRedirectTo:redirectUrl()}});if(resendError)throw resendError;setConfirmationEmail(normalized);setResendCooldown(60);setNotice(`Nuevo correo enviado a ${normalized}. Revisa también Spam, Promociones y No deseados.`);}catch(err){setResendCooldown(60);setError(friendly(err,'No fue posible reenviar el correo de confirmación.'));}finally{setBusy(false);}};
 const submit=async(event:React.FormEvent)=>{event.preventDefault();if(!target)return;setBusy(true);setError('');setNotice('');try{const normalized=email.trim().toLowerCase();if(!normalized.includes('@'))throw new Error('Ingresa un correo válido.');if(password.length<10)throw new Error('La contraseña debe tener al menos 10 caracteres.');rememberDriverInviteToken(inviteCode);window.localStorage.setItem(ONBOARDING_INTENT_KEY,'driver');const db=requireSupabase();if(mode==='register'){if(password!==confirm)throw new Error('Las contraseñas no coinciden.');const{data,error:signUpError}=await db.auth.signUp({email:normalized,password,options:{emailRedirectTo:redirectUrl(),data:{account_kind:'driver'}}});if(signUpError)throw signUpError;if(data.session){window.location.assign(redirectUrl());return;}setConfirmationEmail(normalized);setResendCooldown(60);setNotice(`Te enviamos un enlace de confirmación a ${normalized}. Ábrelo para entrar a ${target.companyName}.`);setPassword('');setConfirm('');}else{const{data,error:signInError}=await db.auth.signInWithPassword({email:normalized,password});if(signInError)throw signInError;if(data.session)window.location.assign(redirectUrl());}}catch(err){setError(friendly(err,mode==='register'?'No fue posible crear tu cuenta.':'No fue posible iniciar sesión.'));}finally{setBusy(false);}};
 return <AuthShell compact eyebrow="Invitación privada de una central" title="Comienza como conductor">
  <div className="flex items-center gap-3"><span className="cg-role-icon h-12 w-12"><CarFront className="h-6 w-6"/></span><div><p className="cg-card-kicker">Central GO · Alta directa</p><h1 className="cg-card-title text-2xl">Únete como conductor</h1></div></div>
  <div className="mt-4 rounded-2xl border border-[var(--cg-border)] bg-[var(--cg-primary-soft)] p-4">{checking?<p className="flex items-center gap-2 text-xs font-black text-[var(--cg-text)]"><Loader2 className="h-4 w-4 animate-spin"/>Validando invitación privada…</p>:target?<><p className="flex items-center gap-2 text-sm font-black text-[var(--cg-text)]"><Building2 className="h-4 w-4 text-[var(--cg-primary)]"/>{target.companyName}</p><p className="mt-1 text-[11px] leading-relaxed text-[var(--cg-muted)]">Esta central ya autorizó tu ingreso. Al crear o iniciar tu cuenta quedarás habilitado para trabajar con ella inmediatamente.</p><p className="mt-2 flex items-center gap-1.5 text-[11px] font-black text-emerald-400"><ShieldCheck className="h-4 w-4"/>No necesitas subir cédula, licencia ni documentación de postulación.</p></>:null}</div>
  {error&&<div className="cg-alert cg-alert-error">{error}</div>}{notice&&<div className="cg-alert cg-alert-success">{notice}</div>}
  {confirmationEmail&&<div className="mt-3 rounded-2xl border border-emerald-500/25 bg-emerald-500/[0.07] p-3"><div className="flex items-start gap-2"><MailCheck className="mt-0.5 h-4 w-4 shrink-0 text-emerald-400"/><div className="min-w-0"><p className="text-xs font-black text-[var(--cg-text)]">Confirma tu correo para continuar</p><p className="mt-1 break-all text-[11px] text-[var(--cg-muted)]">Enviado a <strong className="text-[var(--cg-text)]">{confirmationEmail}</strong>. Si no aparece, revisa Spam, Promociones o No deseados.</p></div></div><button type="button" disabled={busy||resendCooldown>0} onClick={()=>void resendConfirmation()} className="cg-subtle-button mt-3 w-full disabled:opacity-40"><RefreshCw className="h-4 w-4"/>{resendCooldown>0?`Reenviar en ${resendCooldown}s`:'Reenviar correo de confirmación'}</button><button type="button" onClick={()=>{setConfirmationEmail('');setNotice('');setEmail('');}} className="mt-2 w-full text-center text-[11px] font-bold text-[var(--cg-muted)] hover:text-[var(--cg-text)]">Usar otro correo</button></div>}
  <div className="cg-segmented" role="tablist"><button type="button" data-active={mode==='register'} onClick={()=>{setMode('register');setError('');setNotice('');}}>Crear cuenta</button><button type="button" data-active={mode==='login'} onClick={()=>{setMode('login');setError('');setNotice('');}}>Ya tengo cuenta</button></div>
  <button type="button" disabled={busy||checking||!target} onClick={()=>void google()} className="cg-google-button"><span className="cg-google-mark" aria-hidden="true">G</span>{busy?'Conectando…':'Continuar con Google'}</button><div className="cg-divider">o usa tu correo</div>
  <form onSubmit={submit} className="cg-form"><label className="cg-field"><span>Correo electrónico</span><input required type="email" autoComplete="email" value={email} onChange={e=>{setEmail(e.target.value);if(confirmationEmail&&e.target.value.trim().toLowerCase()!==confirmationEmail)setConfirmationEmail('');}} placeholder="tu@correo.com"/></label><label className="cg-field"><span>Contraseña</span><input required minLength={10} type="password" autoComplete={mode==='register'?'new-password':'current-password'} value={password} onChange={e=>setPassword(e.target.value)} placeholder="Mínimo 10 caracteres"/></label>{mode==='register'&&<label className="cg-field"><span>Repetir contraseña</span><input required minLength={10} type="password" autoComplete="new-password" value={confirm} onChange={e=>setConfirm(e.target.value)} placeholder="Repite tu contraseña"/></label>}<button disabled={busy||checking||!target} className="cg-primary-button">{busy&&<Loader2 className="h-4 w-4 animate-spin"/>}{busy?'Procesando…':mode==='register'?'Crear cuenta y entrar a la central':'Entrar a la central'}</button></form>
  <p className="cg-auth-hint">Alta directa autorizada por la central · sin proceso documental de postulación</p>
 </AuthShell>;
};
