import React,{useState} from 'react';
import {requireSupabase} from '../../lib/supabase';
import {useAuth} from '../../context/AuthContext';

type Kind='central'|'sales_partner';
export const OnboardingScreen:React.FC=()=>{const {authUser,refreshIdentity}=useAuth();const [kind,setKind]=useState<Kind|null>(null),[name,setName]=useState(authUser?.user_metadata?.full_name??authUser?.user_metadata?.name??''),[company,setCompany]=useState(''),[phone,setPhone]=useState(''),[city,setCity]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const submit=async(e:React.FormEvent)=>{e.preventDefault();if(!kind)return;setBusy(true);setError('');try{const {error}=await requireSupabase().rpc('centralgo_self_service_onboarding',{p_account_kind:kind,p_name:name,p_phone:phone||null,p_city:city||null,p_country_code:'CL',p_company_name:kind==='central'?company:null});if(error)throw error;await refreshIdentity();}catch(err){setError(err instanceof Error?err.message:'No fue posible crear tu cuenta.');}finally{setBusy(false);}};
 return <main className="mobile-safe-page bg-[#070709] text-white flex items-start justify-center p-4 pt-6 sm:items-center sm:py-8"><section className="w-full max-w-xl rounded-3xl border border-zinc-800 bg-[#0d0d0f] p-5 sm:p-7"><p className="text-xs font-black uppercase tracking-widest text-amber-300">Bienvenido a Central GO</p><h1 className="mt-2 text-2xl font-black">¿Cómo quieres registrarte?</h1><p className="mt-2 text-sm text-zinc-400">Tu prueba gratuita de 5 días comienza cuando termines este registro.</p>
 <div className="mt-6 grid gap-3 sm:grid-cols-2"><button type="button" onClick={()=>setKind('central')} className={`rounded-2xl border p-5 text-left ${kind==='central'?'border-amber-400 bg-amber-400/10':'border-zinc-800 bg-zinc-950'}`}><b className="block">Soy una Central</b><span className="mt-2 block text-xs text-zinc-500">Despacho, mapa, carreras, móviles, conductores y clientes.</span></button><button type="button" onClick={()=>setKind('sales_partner')} className={`rounded-2xl border p-5 text-left ${kind==='sales_partner'?'border-amber-400 bg-amber-400/10':'border-zinc-800 bg-zinc-950'}`}><b className="block">Partner Comercial</b><span className="mt-2 block text-xs text-zinc-500">Ventas, centrales referidas, comisiones y material comercial.</span></button></div>
 {kind&&<form onSubmit={submit} className="mt-6 space-y-3 pb-2"><input required value={name} onChange={e=>setName(e.target.value)} placeholder="Tu nombre" className="w-full rounded-xl border border-zinc-800 bg-zinc-950 px-4 py-3"/><div className="grid gap-3 sm:grid-cols-2"><input required value={phone} onChange={e=>setPhone(e.target.value)} placeholder="Teléfono" className="rounded-xl border border-zinc-800 bg-zinc-950 px-4 py-3"/><input required value={city} onChange={e=>setCity(e.target.value)} placeholder="Ciudad / región" className="rounded-xl border border-zinc-800 bg-zinc-950 px-4 py-3"/></div>{kind==='central'&&<input required value={company} onChange={e=>setCompany(e.target.value)} placeholder="Nombre de la central" className="w-full rounded-xl border border-zinc-800 bg-zinc-950 px-4 py-3"/>}{error&&<div className="rounded-xl bg-rose-500/10 p-3 text-sm text-rose-200">{error}</div>}<button disabled={busy} className="mobile-sticky-action w-full rounded-xl bg-amber-400 p-3.5 font-black text-zinc-950 shadow-2xl shadow-black/60">{busy?'Creando cuenta…':'Comenzar prueba gratuita'}</button><p className="text-center text-[10px] text-zinc-600">Al continuar aceptas las condiciones de uso de Central GO.</p></form>}</section></main>;
};