import React,{useState} from 'react';
import {requireSupabase} from '../../lib/supabase';
import {useAuth} from '../../context/AuthContext';

export const OnboardingScreen:React.FC=()=>{const {authUser,refreshIdentity}=useAuth();const [name,setName]=useState(authUser?.user_metadata?.full_name??authUser?.user_metadata?.name??''),[phone,setPhone]=useState(''),[city,setCity]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const submit=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);setError('');try{const {error}=await requireSupabase().rpc('centralgo_self_service_onboarding',{p_account_kind:'sales_partner',p_name:name,p_phone:phone||null,p_city:city||null,p_country_code:'CL',p_company_name:null});if(error)throw error;await refreshIdentity();}catch(err){setError(err instanceof Error?err.message:'No fue posible crear tu cuenta Partner Comercial.');}finally{setBusy(false);}};
 return <main className="mobile-safe-page bg-[#070709] text-white flex items-start justify-center p-4 pt-6 sm:items-center sm:py-8"><section className="w-full max-w-xl rounded-3xl border border-zinc-800 bg-[#0d0d0f] p-5 sm:p-7"><p className="text-xs font-black uppercase tracking-widest text-amber-300">Registro abierto · Central GO</p><h1 className="mt-2 text-2xl font-black">Crea tu cuenta de Partner Comercial</h1><p className="mt-2 text-sm leading-relaxed text-zinc-400">La cuenta Partner es gratuita y no vence. Desde tu panel podrás registrar tus propias centrales; cada alta quedará vinculada automáticamente a tu código y visible para Superadmin.</p>
 <div className="mt-5 rounded-2xl border border-emerald-500/20 bg-emerald-500/[0.06] p-4"><p className="text-xs font-black text-emerald-300">¿Qué pasa con las centrales?</p><p className="mt-1 text-[11px] leading-relaxed text-zinc-400">Cada central que registres recibe su periodo de prueba de 5 días. Tú puedes seguir usando tu panel comercial aunque una central termine su prueba.</p></div>
 <form onSubmit={submit} className="mt-6 space-y-3 pb-2"><input required value={name} onChange={e=>setName(e.target.value)} placeholder="Tu nombre" className="w-full rounded-xl border border-zinc-800 bg-zinc-950 px-4 py-3"/><div className="grid gap-3 sm:grid-cols-2"><input required value={phone} onChange={e=>setPhone(e.target.value)} placeholder="Teléfono" className="rounded-xl border border-zinc-800 bg-zinc-950 px-4 py-3"/><input required value={city} onChange={e=>setCity(e.target.value)} placeholder="Ciudad / región" className="rounded-xl border border-zinc-800 bg-zinc-950 px-4 py-3"/></div>{error&&<div className="rounded-xl bg-rose-500/10 p-3 text-sm text-rose-200">{error}</div>}<button disabled={busy} className="mobile-sticky-action w-full rounded-xl bg-amber-400 p-3.5 font-black text-zinc-950 shadow-2xl shadow-black/60">{busy?'Creando cuenta…':'Crear mi cuenta Partner Comercial'}</button><p className="text-center text-[10px] text-zinc-600">Registro inmediato · sin aprobación previa · sin tarjeta</p></form></section></main>;
};